import UIKit

// Generated by tools/art/weapons.py. Edit the Python and rerun it; do not
// edit this file by hand.

/// The weapons a run can be started with, and what they throw.
///
/// A held weapon is anchored on its grip and drawn pointing up; a thrown one
/// is anchored at its middle. The drawing primitives these call live in
/// PlaceholderArt+Drawing.swift.
extension PlaceholderArt {

    // MARK: - sai

    /// A sai: one prong to stab with, two to take a blade out of a hand.
    static func sai() -> Sprite {
        let image = render(CGSize(width: 16, height: 36)) { ctx in
            fillPolygon(ctx, [P(9.3, 30), P(9.17, 25.06), P(9.03, 20.22), P(8.9, 15.5), P(8.77, 10.89), P(8.63, 6.39), P(8.5, 2), P(7.5, 2), P(7.37, 6.39), P(7.23, 10.89), P(7.1, 15.5), P(6.97, 20.22), P(6.83, 25.06), P(6.7, 30)], UIColor(rgb: 0xC4CAD2))
            strokePolygon(ctx, [P(9.3, 30), P(9.17, 25.06), P(9.03, 20.22), P(8.9, 15.5), P(8.77, 10.89), P(8.63, 6.39), P(8.5, 2), P(7.5, 2), P(7.37, 6.39), P(7.23, 10.89), P(7.1, 15.5), P(6.97, 20.22), P(6.83, 25.06), P(6.7, 30)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(8, 5), to: P(8, 26), UIColor(rgb: 0xE6EAEE), width: 0.5)
            strokeCurve(ctx, [P(6.4, 25), P(2.8, 20), P(3.6, 12)], UIColor(rgb: 0x767C86), width: 1.6)
            fillPolygon(ctx, [P(4.19, 14.09), P(4, 10.52), P(3.6, 10.48), P(2.61, 13.91)], UIColor(rgb: 0xC4CAD2))
            strokePolygon(ctx, [P(4.19, 14.09), P(4, 10.52), P(3.6, 10.48), P(2.61, 13.91)], UIColor(rgb: 0x0E0C08), width: 0.5)
            strokeCurve(ctx, [P(9.6, 25), P(13.2, 20), P(12.4, 12)], UIColor(rgb: 0x767C86), width: 1.6)
            fillPolygon(ctx, [P(13.39, 13.91), P(12.4, 10.48), P(12, 10.52), P(11.81, 14.09)], UIColor(rgb: 0xC4CAD2))
            strokePolygon(ctx, [P(13.39, 13.91), P(12.4, 10.48), P(12, 10.52), P(11.81, 14.09)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillOval(ctx, CGRect(x: 5.2, y: 24.4, width: 5.6, height: 3.2), UIColor(rgb: 0x5E5A54))
            strokeOval(ctx, CGRect(x: 5.2, y: 24.4, width: 5.6, height: 3.2), UIColor(rgb: 0x0E0C08), width: 0.6)
            fillPolygon(ctx, [P(6.4, 26), P(6.4, 33.5), P(9.6, 33.5), P(9.6, 26)], UIColor(rgb: 0x3A2A2A))
            strokePolygon(ctx, [P(6.4, 26), P(6.4, 33.5), P(9.6, 33.5), P(9.6, 26)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(6.6, 27.4), to: P(9.4, 28.3), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.6, 29.6), to: P(9.4, 30.5), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.6, 31.8), to: P(9.4, 32.7), UIColor(rgb: 0x6B5F5F), width: 0.5)
            fillOval(ctx, CGRect(x: 6.2, y: 33, width: 3.6, height: 2.6), UIColor(rgb: 0x9A7A3A))
            strokeOval(ctx, CGRect(x: 6.2, y: 33, width: 3.6, height: 2.6), UIColor(rgb: 0x0E0C08), width: 0.6)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.2))
    }

    // MARK: - katana

    /// A katana, single-edged and barely curved.
    static func katana() -> Sprite {
        let image = render(CGSize(width: 14, height: 48)) { ctx in
            fillPolygon(ctx, [P(8.39, 33.14), P(8.52, 28.12), P(8.71, 23.08), P(8.94, 18), P(9.24, 12.89), P(9.59, 7.75), P(10, 2.57), P(8.8, 2.43), P(7.93, 7.55), P(7.12, 12.66), P(6.36, 17.75), P(5.65, 22.81), P(5, 27.85), P(4.41, 32.86)], UIColor(rgb: 0xC4CAD2))
            strokePolygon(ctx, [P(8.39, 33.14), P(8.52, 28.12), P(8.71, 23.08), P(8.94, 18), P(9.24, 12.89), P(9.59, 7.75), P(10, 2.57), P(8.8, 2.43), P(7.93, 7.55), P(7.12, 12.66), P(6.36, 17.75), P(5.65, 22.81), P(5, 27.85), P(4.41, 32.86)], UIColor(rgb: 0x0E0C08), width: 0.7)
            strokeCurve(ctx, [P(7.2, 31), P(8.1, 17), P(9.4, 4)], UIColor(rgb: 0xE6EAEE), width: 0.6)
            strokeCurve(ctx, [P(5.6, 31.5), P(6.6, 17.5), P(8.6, 4.5)], UIColor(rgb: 0x93979D), width: 0.5)
            fillPolygon(ctx, [P(6.3, 30), P(10.2, 33), P(6.3, 36), P(2.6, 33)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(6.3, 30), P(10.2, 33), P(6.3, 36), P(2.6, 33)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 5.1, y: 32.1, width: 2.4, height: 2), UIColor(rgb: 0x3A3833))
            fillPolygon(ctx, [P(4.3, 34.5), P(4.3, 45.5), P(7.7, 45.5), P(7.7, 34.5)], UIColor(rgb: 0x3A2A2A))
            strokePolygon(ctx, [P(4.3, 34.5), P(4.3, 45.5), P(7.7, 45.5), P(7.7, 34.5)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(4.5, 35.9), to: P(7.5, 36.8), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(4.5, 38.1), to: P(7.5, 39), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(4.5, 40.3), to: P(7.5, 41.2), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(4.5, 42.5), to: P(7.5, 43.4), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(4.5, 44.7), to: P(7.5, 45.6), UIColor(rgb: 0x6B5F5F), width: 0.5)
            fillPolygon(ctx, [P(4.3, 45), P(7.7, 45), P(7.4, 47.2), P(4.6, 47.2)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(4.3, 45), P(7.7, 45), P(7.4, 47.2), P(4.6, 47.2)], UIColor(rgb: 0x0E0C08), width: 0.6)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.2))
    }

    // MARK: - claymore

    /// A claymore: a two-handed greatsword with a blade as long as a child is tall.
    static func claymore() -> Sprite {
        let image = render(CGSize(width: 22, height: 66)) { ctx in
            fillPolygon(ctx, [P(7.6, 43), P(7.7, 12), P(8.4, 7.4), P(11, 1.6), P(13.6, 7.4), P(14.3, 12), P(14.4, 43)], UIColor(rgb: 0xC4CAD2))
            strokePolygon(ctx, [P(7.6, 43), P(7.7, 12), P(8.4, 7.4), P(11, 1.6), P(13.6, 7.4), P(14.3, 12), P(14.4, 43)], UIColor(rgb: 0x0E0C08), width: 0.8)
            fillPolygon(ctx, [P(11, 43), P(11, 8), P(11, 2.6), P(14.3, 12), P(14.4, 43)], UIColor(rgb: 0xA8ADB4))
            stroke(ctx, from: P(11, 41), to: P(11, 10), UIColor(rgb: 0x81858A), width: 1.4)
            stroke(ctx, from: P(9.9, 41), to: P(9.9, 10), UIColor(rgb: 0xE6EAEE), width: 0.5)
            stroke(ctx, from: P(12.1, 41), to: P(12.1, 10), UIColor(rgb: 0x767C86), width: 0.5)
            stroke(ctx, from: P(8.5, 42), to: P(8.5, 12), UIColor(rgb: 0xE6EAEE), width: 0.5)
            stroke(ctx, from: P(10, 36.6), to: P(12, 36.6), UIColor(rgb: 0x88723F), width: 0.5)
            stroke(ctx, from: P(10, 33.8), to: P(12, 33.8), UIColor(rgb: 0x88723F), width: 0.5)
            stroke(ctx, from: P(10, 31), to: P(12, 31), UIColor(rgb: 0x88723F), width: 0.5)
            fillPolygon(ctx, [P(2.37, 46.89), P(5.27, 46.56), P(8.13, 46.37), P(11, 46.3), P(13.87, 46.37), P(16.73, 46.56), P(19.63, 46.89), P(19.97, 43.91), P(17, 43.57), P(14, 43.37), P(11, 43.3), P(8, 43.37), P(5, 43.57), P(2.03, 43.91)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(2.37, 46.89), P(5.27, 46.56), P(8.13, 46.37), P(11, 46.3), P(13.87, 46.37), P(16.73, 46.56), P(19.63, 46.89), P(19.97, 43.91), P(17, 43.57), P(14, 43.37), P(11, 43.3), P(8, 43.37), P(5, 43.57), P(2.03, 43.91)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(1.2, 43.4), P(3.4, 42.2), P(3.8, 46.6), P(1.6, 47.2)], UIColor(rgb: 0x3A3833))
            strokePolygon(ctx, [P(1.2, 43.4), P(3.4, 42.2), P(3.8, 46.6), P(1.6, 47.2)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillPolygon(ctx, [P(20.8, 43.4), P(18.6, 42.2), P(18.2, 46.6), P(20.4, 47.2)], UIColor(rgb: 0x3A3833))
            strokePolygon(ctx, [P(20.8, 43.4), P(18.6, 42.2), P(18.2, 46.6), P(20.4, 47.2)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(3.6, 44.4), to: P(18.4, 44.4), UIColor(rgb: 0x86837E), width: 0.5)
            fillOval(ctx, CGRect(x: 9.5, y: 43.6, width: 3, height: 3), UIColor(rgb: 0x9A7A3A))
            strokeOval(ctx, CGRect(x: 9.5, y: 43.6, width: 3, height: 3), UIColor(rgb: 0x0E0C08), width: 0.6)
            fillPolygon(ctx, [P(9.3, 47), P(9.3, 59), P(12.7, 59), P(12.7, 47)], UIColor(rgb: 0x3A2A2A))
            strokePolygon(ctx, [P(9.3, 47), P(9.3, 59), P(12.7, 59), P(12.7, 47)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(9.5, 48.4), to: P(12.5, 49.3), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(9.5, 50.6), to: P(12.5, 51.5), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(9.5, 52.8), to: P(12.5, 53.7), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(9.5, 55), to: P(12.5, 55.9), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(9.5, 57.2), to: P(12.5, 58.1), UIColor(rgb: 0x6B5F5F), width: 0.5)
            fillOval(ctx, CGRect(x: 7.8, y: 58.4, width: 6.4, height: 5.6), UIColor(rgb: 0x9A7A3A))
            strokeOval(ctx, CGRect(x: 7.8, y: 58.4, width: 6.4, height: 5.6), UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 9.4, y: 60, width: 3.2, height: 2.6), UIColor(rgb: 0xA2261E))
            strokeOval(ctx, CGRect(x: 9.4, y: 60, width: 3.2, height: 2.6), UIColor(rgb: 0x0E0C08), width: 0.4)
            fillOval(ctx, CGRect(x: 9.95, y: 59.95, width: 1.1, height: 1.1), UIColor(rgb: 0xF2A29A))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.16))
    }

    // MARK: - dualDaggers

    /// Two daggers, crossed: nothing here is meant to be parried.
    static func dualDaggers() -> Sprite {
        let image = render(CGSize(width: 24, height: 34)) { ctx in
            fillPolygon(ctx, [P(9.35, 24.35), P(10.06, 20.95), P(10.78, 17.49), P(11.52, 13.97), P(12.28, 10.4), P(13.05, 6.77), P(13.84, 3.09), P(13.16, 2.91), P(12.03, 6.51), P(10.92, 10.04), P(9.83, 13.53), P(8.75, 16.96), P(7.69, 20.33), P(6.65, 23.65)], UIColor(rgb: 0xC4CAD2))
            strokePolygon(ctx, [P(9.35, 24.35), P(10.06, 20.95), P(10.78, 17.49), P(11.52, 13.97), P(12.28, 10.4), P(13.05, 6.77), P(13.84, 3.09), P(13.16, 2.91), P(12.03, 6.51), P(10.92, 10.04), P(9.83, 13.53), P(8.75, 16.96), P(7.69, 20.33), P(6.65, 23.65)], UIColor(rgb: 0x0E0C08), width: 0.6)
            strokeCurve(ctx, [P(8.4, 22), P(11, 12), P(13, 4.5)], UIColor(rgb: 0xE6EAEE), width: 0.5)
            fillPolygon(ctx, [P(5.84, 25.57), P(10.64, 24.37), P(10.16, 22.43), P(5.36, 23.63)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(5.84, 25.57), P(10.64, 24.37), P(10.16, 22.43), P(5.36, 23.63)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillPolygon(ctx, [P(6, 25), P(6, 31), P(8.8, 31), P(8.8, 25)], UIColor(rgb: 0x3A2A2A))
            strokePolygon(ctx, [P(6, 25), P(6, 31), P(8.8, 31), P(8.8, 25)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(6.2, 26.4), to: P(8.6, 27.3), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.2, 28.6), to: P(8.6, 29.5), UIColor(rgb: 0x6B5F5F), width: 0.5)
            fillOval(ctx, CGRect(x: 5.9, y: 30.6, width: 3, height: 2.2), UIColor(rgb: 0x9A7A3A))
            strokeOval(ctx, CGRect(x: 5.9, y: 30.6, width: 3, height: 2.2), UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(17.35, 23.65), P(16.31, 20.33), P(15.25, 16.96), P(14.17, 13.53), P(13.08, 10.04), P(11.97, 6.51), P(10.84, 2.91), P(10.16, 3.09), P(10.95, 6.77), P(11.72, 10.4), P(12.48, 13.97), P(13.22, 17.49), P(13.94, 20.95), P(14.65, 24.35)], UIColor(rgb: 0xC4CAD2))
            strokePolygon(ctx, [P(17.35, 23.65), P(16.31, 20.33), P(15.25, 16.96), P(14.17, 13.53), P(13.08, 10.04), P(11.97, 6.51), P(10.84, 2.91), P(10.16, 3.09), P(10.95, 6.77), P(11.72, 10.4), P(12.48, 13.97), P(13.22, 17.49), P(13.94, 20.95), P(14.65, 24.35)], UIColor(rgb: 0x0E0C08), width: 0.6)
            strokeCurve(ctx, [P(15.6, 22), P(13, 12), P(11, 4.5)], UIColor(rgb: 0xE6EAEE), width: 0.5)
            fillPolygon(ctx, [P(13.84, 25.57), P(18.64, 24.37), P(18.16, 22.43), P(13.36, 23.63)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(13.84, 25.57), P(18.64, 24.37), P(18.16, 22.43), P(13.36, 23.63)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillPolygon(ctx, [P(15.2, 25), P(15.2, 31), P(18, 31), P(18, 25)], UIColor(rgb: 0x3A2A2A))
            strokePolygon(ctx, [P(15.2, 25), P(15.2, 31), P(18, 31), P(18, 25)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(15.4, 26.4), to: P(17.8, 27.3), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(15.4, 28.6), to: P(17.8, 29.5), UIColor(rgb: 0x6B5F5F), width: 0.5)
            fillOval(ctx, CGRect(x: 15.1, y: 30.6, width: 3, height: 2.2), UIColor(rgb: 0x9A7A3A))
            strokeOval(ctx, CGRect(x: 15.1, y: 30.6, width: 3, height: 2.2), UIColor(rgb: 0x0E0C08), width: 0.5)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.3))
    }

    // MARK: - warHammer

    /// A war hammer: one flat face, one beak, and no subtlety.
    static func warHammer() -> Sprite {
        let image = render(CGSize(width: 24, height: 48)) { ctx in
            fillPolygon(ctx, [P(13.2, 44), P(13.15, 38.11), P(13.1, 32.44), P(13.05, 27), P(13, 21.78), P(12.95, 16.78), P(12.9, 12), P(10.1, 12), P(10.05, 16.78), P(10, 21.78), P(9.95, 27), P(9.9, 32.44), P(9.85, 38.11), P(9.8, 44)], UIColor(rgb: 0x5A3E26))
            strokePolygon(ctx, [P(13.2, 44), P(13.15, 38.11), P(13.1, 32.44), P(13.05, 27), P(13, 21.78), P(12.95, 16.78), P(12.9, 12), P(10.1, 12), P(10.05, 16.78), P(10, 21.78), P(9.95, 27), P(9.9, 32.44), P(9.85, 38.11), P(9.8, 44)], UIColor(rgb: 0x0E0C08), width: 0.7)
            strokeCurve(ctx, [P(10.6, 42), P(10.6, 14)], UIColor(rgb: 0x33220F), width: 0.5)
            fillPolygon(ctx, [P(4.5, 9), P(14.5, 7.5), P(15.5, 17.5), P(5.5, 19)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(4.5, 9), P(14.5, 7.5), P(15.5, 17.5), P(5.5, 19)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillPolygon(ctx, [P(10, 8.2), P(14.5, 7.5), P(15.5, 17.5), P(11, 18.3)], UIColor(rgb: 0x7A7772))
            fillPolygon(ctx, [P(4.5, 9), P(5.5, 19), P(3.2, 18.2), P(2.4, 9.8)], UIColor(rgb: 0x3A3833))
            strokePolygon(ctx, [P(4.5, 9), P(5.5, 19), P(3.2, 18.2), P(2.4, 9.8)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 5.8, y: 10.3, width: 1.4, height: 1.4), UIColor(rgb: 0x7A5A40))
            fillOval(ctx, CGRect(x: 5.8, y: 15.3, width: 1.4, height: 1.4), UIColor(rgb: 0x7A5A40))
            fillPolygon(ctx, [P(15, 9.5), P(22, 11.5), P(15.6, 16)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(15, 9.5), P(22, 11.5), P(15.6, 16)], UIColor(rgb: 0x0E0C08), width: 0.8)
            fillPolygon(ctx, [P(15, 9.5), P(22, 11.5), P(18.5, 12.4)], UIColor(rgb: 0x86837E))
            fillPolygon(ctx, [P(10.3, 6.5), P(10.3, 10), P(12.7, 10), P(12.7, 6.5)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(10.3, 6.5), P(10.3, 10), P(12.7, 10), P(12.7, 6.5)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillPolygon(ctx, [P(9.7, 34), P(9.7, 45), P(13.3, 45), P(13.3, 34)], UIColor(rgb: 0x3A2A2A))
            strokePolygon(ctx, [P(9.7, 34), P(9.7, 45), P(13.3, 45), P(13.3, 34)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(9.9, 35.4), to: P(13.1, 36.3), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(9.9, 37.6), to: P(13.1, 38.5), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(9.9, 39.8), to: P(13.1, 40.7), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(9.9, 42), to: P(13.1, 42.9), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(9.9, 44.2), to: P(13.1, 45.1), UIColor(rgb: 0x6B5F5F), width: 0.5)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.2))
    }

    // MARK: - boStaff

    /// A bo staff, iron-shod at both ends and worn smooth in the middle.
    static func boStaff() -> Sprite {
        let image = render(CGSize(width: 10, height: 60)) { ctx in
            fillPolygon(ctx, [P(6.7, 57), P(6.7, 48), P(6.7, 39), P(6.7, 30), P(6.7, 21), P(6.7, 12), P(6.7, 3), P(3.3, 3), P(3.3, 12), P(3.3, 21), P(3.3, 30), P(3.3, 39), P(3.3, 48), P(3.3, 57)], UIColor(rgb: 0x7E5C36))
            strokePolygon(ctx, [P(6.7, 57), P(6.7, 48), P(6.7, 39), P(6.7, 30), P(6.7, 21), P(6.7, 12), P(6.7, 3), P(3.3, 3), P(3.3, 12), P(3.3, 21), P(3.3, 30), P(3.3, 39), P(3.3, 48), P(3.3, 57)], UIColor(rgb: 0x0E0C08), width: 0.7)
            strokeCurve(ctx, [P(4, 54), P(4, 6)], UIColor(rgb: 0x33220F), width: 0.5)
            fillPolygon(ctx, [P(3.1, 3), P(6.9, 3), P(6.9, 9), P(3.1, 9)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(3.1, 3), P(6.9, 3), P(6.9, 9), P(3.1, 9)], UIColor(rgb: 0x0E0C08), width: 0.7)
            stroke(ctx, from: P(3.4, 5), to: P(6.6, 5), UIColor(rgb: 0x8E8B87), width: 0.5)
            fillPolygon(ctx, [P(3.1, 51), P(6.9, 51), P(6.9, 57), P(3.1, 57)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(3.1, 51), P(6.9, 51), P(6.9, 57), P(3.1, 57)], UIColor(rgb: 0x0E0C08), width: 0.7)
            stroke(ctx, from: P(3.4, 53), to: P(6.6, 53), UIColor(rgb: 0x8E8B87), width: 0.5)
            fillPolygon(ctx, [P(3.1, 24), P(3.1, 36), P(6.9, 36), P(6.9, 24)], UIColor(rgb: 0x3A2A2A))
            strokePolygon(ctx, [P(3.1, 24), P(3.1, 36), P(6.9, 36), P(6.9, 24)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(3.3, 25.4), to: P(6.7, 26.3), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(3.3, 27.6), to: P(6.7, 28.5), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(3.3, 29.8), to: P(6.7, 30.7), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(3.3, 32), to: P(6.7, 32.9), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(3.3, 34.2), to: P(6.7, 35.1), UIColor(rgb: 0x6B5F5F), width: 0.5)
            fillPolygon(ctx, [P(3.2, 20.8), P(6.8, 20.8), P(6.8, 19.2), P(3.2, 19.2)], UIColor(rgb: 0xB8A88C))
            strokePolygon(ctx, [P(3.2, 20.8), P(6.8, 20.8), P(6.8, 19.2), P(3.2, 19.2)], UIColor(rgb: 0x0E0C08), width: 0.4)
            fillPolygon(ctx, [P(3.2, 40.8), P(6.8, 40.8), P(6.8, 39.2), P(3.2, 39.2)], UIColor(rgb: 0xB8A88C))
            strokePolygon(ctx, [P(3.2, 40.8), P(6.8, 40.8), P(6.8, 39.2), P(3.2, 39.2)], UIColor(rgb: 0x0E0C08), width: 0.4)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.5))
    }

    // MARK: - flail

    /// A flail. Blocking it is not the same as being safe from it.
    static func flail() -> Sprite {
        let image = render(CGSize(width: 20, height: 46)) { ctx in
            fillPolygon(ctx, [P(8.6, 43), P(8.55, 39.97), P(8.5, 36.89), P(8.45, 33.75), P(8.4, 30.56), P(8.35, 27.31), P(8.3, 24), P(5.7, 24), P(5.65, 27.31), P(5.6, 30.56), P(5.55, 33.75), P(5.5, 36.89), P(5.45, 39.97), P(5.4, 43)], UIColor(rgb: 0x5A3E26))
            strokePolygon(ctx, [P(8.6, 43), P(8.55, 39.97), P(8.5, 36.89), P(8.45, 33.75), P(8.4, 30.56), P(8.35, 27.31), P(8.3, 24), P(5.7, 24), P(5.65, 27.31), P(5.6, 30.56), P(5.55, 33.75), P(5.5, 36.89), P(5.45, 39.97), P(5.4, 43)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(5.3, 32), P(5.3, 44), P(8.7, 44), P(8.7, 32)], UIColor(rgb: 0x3A2A2A))
            strokePolygon(ctx, [P(5.3, 32), P(5.3, 44), P(8.7, 44), P(8.7, 32)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(5.5, 33.4), to: P(8.5, 34.3), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(5.5, 35.6), to: P(8.5, 36.5), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(5.5, 37.8), to: P(8.5, 38.7), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(5.5, 40), to: P(8.5, 40.9), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(5.5, 42.2), to: P(8.5, 43.1), UIColor(rgb: 0x6B5F5F), width: 0.5)
            fillPolygon(ctx, [P(5.4, 22.5), P(8.6, 22.5), P(8.6, 25.5), P(5.4, 25.5)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(5.4, 22.5), P(8.6, 22.5), P(8.6, 25.5), P(5.4, 25.5)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 6.1, y: 18.1, width: 3, height: 3.8), UIColor(rgb: 0x5E5A54))
            strokeOval(ctx, CGRect(x: 6.1, y: 18.1, width: 3, height: 3.8), UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 6.8, y: 18.9, width: 1.6, height: 2.2), UIColor(rgb: 0x3A3833))
            fillOval(ctx, CGRect(x: 7.5, y: 14.9, width: 3, height: 3.8), UIColor(rgb: 0x5E5A54))
            strokeOval(ctx, CGRect(x: 7.5, y: 14.9, width: 3, height: 3.8), UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 8.2, y: 15.7, width: 1.6, height: 2.2), UIColor(rgb: 0x3A3833))
            fillOval(ctx, CGRect(x: 9.5, y: 12.3, width: 3, height: 3.8), UIColor(rgb: 0x5E5A54))
            strokeOval(ctx, CGRect(x: 9.5, y: 12.3, width: 3, height: 3.8), UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 10.2, y: 13.1, width: 1.6, height: 2.2), UIColor(rgb: 0x3A3833))
            fillOval(ctx, CGRect(x: 11.9, y: 10.5, width: 3, height: 3.8), UIColor(rgb: 0x5E5A54))
            strokeOval(ctx, CGRect(x: 11.9, y: 10.5, width: 3, height: 3.8), UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 12.6, y: 11.3, width: 1.6, height: 2.2), UIColor(rgb: 0x3A3833))
            fillPolygon(ctx, [P(16.3, 9), P(15.2, 2.6), P(14.8, 2.6), P(13.7, 9)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(16.3, 9), P(15.2, 2.6), P(14.8, 2.6), P(13.7, 9)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(15.32, 10.26), P(21.25, 7.59), P(21.15, 7.21), P(14.68, 7.74)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(15.32, 10.26), P(21.25, 7.59), P(21.15, 7.21), P(14.68, 7.74)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(14.04, 9.88), P(19.25, 13.94), P(19.55, 13.66), P(15.96, 8.12)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(14.04, 9.88), P(19.25, 13.94), P(19.55, 13.66), P(15.96, 8.12)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(14.04, 8.12), P(10.45, 13.66), P(10.75, 13.94), P(15.96, 9.88)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(14.04, 8.12), P(10.45, 13.66), P(10.75, 13.94), P(15.96, 9.88)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(15.32, 7.74), P(8.85, 7.21), P(8.75, 7.59), P(14.68, 10.26)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(15.32, 7.74), P(8.85, 7.21), P(8.75, 7.59), P(14.68, 10.26)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillOval(ctx, CGRect(x: 10.6, y: 4.6, width: 8.8, height: 8.8), UIColor(rgb: 0x54514B))
            strokeOval(ctx, CGRect(x: 10.6, y: 4.6, width: 8.8, height: 8.8), UIColor(rgb: 0x0E0C08), width: 0.9)
            fillOval(ctx, CGRect(x: 12, y: 6, width: 4.4, height: 4), UIColor(rgb: 0x817E79))
            fillOval(ctx, CGRect(x: 12.4, y: 6.2, width: 2, height: 2), UIColor(rgb: 0xAEACA9))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.2))
    }

    // MARK: - boomerang

    /// A boomerang, carved from one bent piece and burnt with marks.
    static func boomerang() -> Sprite {
        let image = render(CGSize(width: 30, height: 30)) { ctx in
            fillOval(ctx, CGRect(x: 21.6, y: 11.6, width: 6.8, height: 6.8), UIColor(rgb: 0x7E5C36))
            strokeOval(ctx, CGRect(x: 21.6, y: 11.6, width: 6.8, height: 6.8), UIColor(rgb: 0x0E0C08), width: 0.9)
            fillPolygon(ctx, [P(26.76, 12.33), P(23.73, 10.58), P(20.7, 8.83), P(17.68, 7.08), P(14.65, 5.33), P(11.62, 3.58), P(8.6, 1.83), P(6.4, 5.17), P(9.21, 7.26), P(12.02, 9.34), P(14.82, 11.42), P(17.63, 13.51), P(20.44, 15.59), P(23.24, 17.67)], UIColor(rgb: 0x7E5C36))
            strokePolygon(ctx, [P(26.76, 12.33), P(23.73, 10.58), P(20.7, 8.83), P(17.68, 7.08), P(14.65, 5.33), P(11.62, 3.58), P(8.6, 1.83), P(6.4, 5.17), P(9.21, 7.26), P(12.02, 9.34), P(14.82, 11.42), P(17.63, 13.51), P(20.44, 15.59), P(23.24, 17.67)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillPolygon(ctx, [P(23.24, 12.33), P(20.44, 14.41), P(17.63, 16.49), P(14.82, 18.58), P(12.02, 20.66), P(9.21, 22.74), P(6.4, 24.83), P(8.6, 28.17), P(11.62, 26.42), P(14.65, 24.67), P(17.68, 22.92), P(20.7, 21.17), P(23.73, 19.42), P(26.76, 17.67)], UIColor(rgb: 0x7E5C36))
            strokePolygon(ctx, [P(23.24, 12.33), P(20.44, 14.41), P(17.63, 16.49), P(14.82, 18.58), P(12.02, 20.66), P(9.21, 22.74), P(6.4, 24.83), P(8.6, 28.17), P(11.62, 26.42), P(14.65, 24.67), P(17.68, 22.92), P(20.7, 21.17), P(23.73, 19.42), P(26.76, 17.67)], UIColor(rgb: 0x0E0C08), width: 0.9)
            strokeCurve(ctx, [P(9, 5.4), P(17, 10.4), P(23.4, 14)], UIColor(rgb: 0x33220F), width: 0.8)
            strokeCurve(ctx, [P(9, 24.6), P(17, 19.6), P(23.4, 16)], UIColor(rgb: 0x33220F), width: 0.8)
            stroke(ctx, from: P(10.3, 6.2), to: P(12.7, 7.8), UIColor(rgb: 0x513722), width: 0.6)
            stroke(ctx, from: P(15.8, 10.2), to: P(18.2, 11.8), UIColor(rgb: 0x513722), width: 0.6)
            stroke(ctx, from: P(15.8, 18.2), to: P(18.2, 19.8), UIColor(rgb: 0x513722), width: 0.6)
            stroke(ctx, from: P(10.3, 22.2), to: P(12.7, 23.8), UIColor(rgb: 0x513722), width: 0.6)
            fillPolygon(ctx, [P(5.4, 1.8), P(10, 4.4), P(6.4, 6.2)], UIColor(rgb: 0x48311E))
            strokePolygon(ctx, [P(5.4, 1.8), P(10, 4.4), P(6.4, 6.2)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(5.4, 28.2), P(10, 25.6), P(6.4, 23.8)], UIColor(rgb: 0x48311E))
            strokePolygon(ctx, [P(5.4, 28.2), P(10, 25.6), P(6.4, 23.8)], UIColor(rgb: 0x0E0C08), width: 0.5)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.5))
    }

    // MARK: - emberWand

    /// A wand with a coal in it that has never gone out.
    static func emberWand() -> Sprite {
        let image = render(CGSize(width: 16, height: 34)) { ctx in
            fillPolygon(ctx, [P(9.4, 31), P(9.35, 28.06), P(9.3, 25.22), P(9.25, 22.5), P(9.2, 19.89), P(9.15, 17.39), P(9.1, 15), P(6.9, 15), P(6.85, 17.39), P(6.8, 19.89), P(6.75, 22.5), P(6.7, 25.22), P(6.65, 28.06), P(6.6, 31)], UIColor(rgb: 0x4A2A18))
            strokePolygon(ctx, [P(9.4, 31), P(9.35, 28.06), P(9.3, 25.22), P(9.25, 22.5), P(9.2, 19.89), P(9.15, 17.39), P(9.1, 15), P(6.9, 15), P(6.85, 17.39), P(6.8, 19.89), P(6.75, 22.5), P(6.7, 25.22), P(6.65, 28.06), P(6.6, 31)], UIColor(rgb: 0x0E0C08), width: 0.6)
            strokeCurve(ctx, [P(7.2, 30), P(7.2, 16)], UIColor(rgb: 0x2C190E), width: 0.5)
            fillPolygon(ctx, [P(6.6, 16.6), P(9.4, 16.6), P(9.4, 14.2), P(6.6, 14.2)], UIColor(rgb: 0x9A7A3A))
            strokePolygon(ctx, [P(6.6, 16.6), P(9.4, 16.6), P(9.4, 14.2), P(6.6, 14.2)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(7.2, 14.65), P(7.2, 8.02), P(6.4, 7.98), P(5.6, 14.55)], UIColor(rgb: 0x9A7A3A))
            strokePolygon(ctx, [P(7.2, 14.65), P(7.2, 8.02), P(6.4, 7.98), P(5.6, 14.55)], UIColor(rgb: 0x0E0C08), width: 0.4)
            fillPolygon(ctx, [P(10.4, 14.55), P(9.6, 7.98), P(8.8, 8.02), P(8.8, 14.65)], UIColor(rgb: 0x9A7A3A))
            strokePolygon(ctx, [P(10.4, 14.55), P(9.6, 7.98), P(8.8, 8.02), P(8.8, 14.65)], UIColor(rgb: 0x0E0C08), width: 0.4)
            radialGradient(ctx, center: P(8, 8), radius: 9, inner: UIColor(rgb: 0xFFC24A, alpha: 0.7), outer: UIColor(rgb: 0xFFC24A, alpha: 0))
            fillPolygon(ctx, [P(8, 2.5), P(12, 7), P(9.6, 13), P(6.4, 13), P(4, 7)], UIColor(rgb: 0xE2601A))
            strokePolygon(ctx, [P(8, 2.5), P(12, 7), P(9.6, 13), P(6.4, 13), P(4, 7)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 6.2, y: 6, width: 2, height: 2), UIColor(rgb: 0xF1B797))
            fillPolygon(ctx, [P(6.5, 22), P(6.5, 32), P(9.5, 32), P(9.5, 22)], UIColor(rgb: 0x3A2A2A))
            strokePolygon(ctx, [P(6.5, 22), P(6.5, 32), P(9.5, 32), P(9.5, 22)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(6.7, 23.4), to: P(9.3, 24.3), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.7, 25.6), to: P(9.3, 26.5), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.7, 27.8), to: P(9.3, 28.7), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.7, 30), to: P(9.3, 30.9), UIColor(rgb: 0x6B5F5F), width: 0.5)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.2))
    }

    // MARK: - rimeWand

    /// A wand ending in a splinter of ice that will not melt.
    static func rimeWand() -> Sprite {
        let image = render(CGSize(width: 16, height: 34)) { ctx in
            fillPolygon(ctx, [P(9.4, 31), P(9.35, 28.06), P(9.3, 25.22), P(9.25, 22.5), P(9.2, 19.89), P(9.15, 17.39), P(9.1, 15), P(6.9, 15), P(6.85, 17.39), P(6.8, 19.89), P(6.75, 22.5), P(6.7, 25.22), P(6.65, 28.06), P(6.6, 31)], UIColor(rgb: 0x2A3A46))
            strokePolygon(ctx, [P(9.4, 31), P(9.35, 28.06), P(9.3, 25.22), P(9.25, 22.5), P(9.2, 19.89), P(9.15, 17.39), P(9.1, 15), P(6.9, 15), P(6.85, 17.39), P(6.8, 19.89), P(6.75, 22.5), P(6.7, 25.22), P(6.65, 28.06), P(6.6, 31)], UIColor(rgb: 0x0E0C08), width: 0.6)
            strokeCurve(ctx, [P(7.2, 30), P(7.2, 16)], UIColor(rgb: 0x19222A), width: 0.5)
            fillPolygon(ctx, [P(6.6, 16.6), P(9.4, 16.6), P(9.4, 14.2), P(6.6, 14.2)], UIColor(rgb: 0x9A7A3A))
            strokePolygon(ctx, [P(6.6, 16.6), P(9.4, 16.6), P(9.4, 14.2), P(6.6, 14.2)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(7.2, 14.65), P(7.2, 8.02), P(6.4, 7.98), P(5.6, 14.55)], UIColor(rgb: 0x9A7A3A))
            strokePolygon(ctx, [P(7.2, 14.65), P(7.2, 8.02), P(6.4, 7.98), P(5.6, 14.55)], UIColor(rgb: 0x0E0C08), width: 0.4)
            fillPolygon(ctx, [P(10.4, 14.55), P(9.6, 7.98), P(8.8, 8.02), P(8.8, 14.65)], UIColor(rgb: 0x9A7A3A))
            strokePolygon(ctx, [P(10.4, 14.55), P(9.6, 7.98), P(8.8, 8.02), P(8.8, 14.65)], UIColor(rgb: 0x0E0C08), width: 0.4)
            radialGradient(ctx, center: P(8, 8), radius: 9, inner: UIColor(rgb: 0x3E7E9E, alpha: 0.7), outer: UIColor(rgb: 0x3E7E9E, alpha: 0))
            fillPolygon(ctx, [P(8, 1.5), P(11.4, 8.5), P(8, 13.4), P(4.6, 8.5)], UIColor(rgb: 0x8CD0E8))
            strokePolygon(ctx, [P(8, 1.5), P(11.4, 8.5), P(8, 13.4), P(4.6, 8.5)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 6.2, y: 6, width: 2, height: 2), UIColor(rgb: 0xCBE9F4))
            fillPolygon(ctx, [P(6.5, 22), P(6.5, 32), P(9.5, 32), P(9.5, 22)], UIColor(rgb: 0x3A2A2A))
            strokePolygon(ctx, [P(6.5, 22), P(6.5, 32), P(9.5, 32), P(9.5, 22)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(6.7, 23.4), to: P(9.3, 24.3), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.7, 25.6), to: P(9.3, 26.5), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.7, 27.8), to: P(9.3, 28.7), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.7, 30), to: P(9.3, 30.9), UIColor(rgb: 0x6B5F5F), width: 0.5)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.2))
    }

    // MARK: - stormWand

    /// A wand holding a charge that keeps trying to leave.
    static func stormWand() -> Sprite {
        let image = render(CGSize(width: 16, height: 34)) { ctx in
            fillPolygon(ctx, [P(9.4, 31), P(9.35, 28.06), P(9.3, 25.22), P(9.25, 22.5), P(9.2, 19.89), P(9.15, 17.39), P(9.1, 15), P(6.9, 15), P(6.85, 17.39), P(6.8, 19.89), P(6.75, 22.5), P(6.7, 25.22), P(6.65, 28.06), P(6.6, 31)], UIColor(rgb: 0x2E2838))
            strokePolygon(ctx, [P(9.4, 31), P(9.35, 28.06), P(9.3, 25.22), P(9.25, 22.5), P(9.2, 19.89), P(9.15, 17.39), P(9.1, 15), P(6.9, 15), P(6.85, 17.39), P(6.8, 19.89), P(6.75, 22.5), P(6.7, 25.22), P(6.65, 28.06), P(6.6, 31)], UIColor(rgb: 0x0E0C08), width: 0.6)
            strokeCurve(ctx, [P(7.2, 30), P(7.2, 16)], UIColor(rgb: 0x1B1821), width: 0.5)
            fillPolygon(ctx, [P(6.6, 16.6), P(9.4, 16.6), P(9.4, 14.2), P(6.6, 14.2)], UIColor(rgb: 0x9A7A3A))
            strokePolygon(ctx, [P(6.6, 16.6), P(9.4, 16.6), P(9.4, 14.2), P(6.6, 14.2)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(7.2, 14.65), P(7.2, 8.02), P(6.4, 7.98), P(5.6, 14.55)], UIColor(rgb: 0x9A7A3A))
            strokePolygon(ctx, [P(7.2, 14.65), P(7.2, 8.02), P(6.4, 7.98), P(5.6, 14.55)], UIColor(rgb: 0x0E0C08), width: 0.4)
            fillPolygon(ctx, [P(10.4, 14.55), P(9.6, 7.98), P(8.8, 8.02), P(8.8, 14.65)], UIColor(rgb: 0x9A7A3A))
            strokePolygon(ctx, [P(10.4, 14.55), P(9.6, 7.98), P(8.8, 8.02), P(8.8, 14.65)], UIColor(rgb: 0x0E0C08), width: 0.4)
            radialGradient(ctx, center: P(8, 8), radius: 9, inner: UIColor(rgb: 0xF2E4FF, alpha: 0.7), outer: UIColor(rgb: 0xF2E4FF, alpha: 0))
            fillPolygon(ctx, [P(8.6, 2), P(11.8, 6.8), P(9, 8.4), P(11, 13.4), P(5, 8.6), P(7.8, 7.2), P(5.4, 4)], UIColor(rgb: 0xC9A6FF))
            strokePolygon(ctx, [P(8.6, 2), P(11.8, 6.8), P(9, 8.4), P(11, 13.4), P(5, 8.6), P(7.8, 7.2), P(5.4, 4)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 6.2, y: 6, width: 2, height: 2), UIColor(rgb: 0xE6D6FF))
            fillPolygon(ctx, [P(6.5, 22), P(6.5, 32), P(9.5, 32), P(9.5, 22)], UIColor(rgb: 0x3A2A2A))
            strokePolygon(ctx, [P(6.5, 22), P(6.5, 32), P(9.5, 32), P(9.5, 22)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(6.7, 23.4), to: P(9.3, 24.3), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.7, 25.6), to: P(9.3, 26.5), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.7, 27.8), to: P(9.3, 28.7), UIColor(rgb: 0x6B5F5F), width: 0.5)
            stroke(ctx, from: P(6.7, 30), to: P(9.3, 30.9), UIColor(rgb: 0x6B5F5F), width: 0.5)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.2))
    }

    // MARK: - projectileBoomerang

    /// The boomerang, mid-flight.
    static func projectileBoomerang() -> Sprite {
        let image = render(CGSize(width: 22, height: 22)) { ctx in
            radialGradient(ctx, center: P(11, 11), radius: 11, inner: UIColor(rgb: 0xB8A88C, alpha: 0.25), outer: UIColor(rgb: 0xB8A88C, alpha: 0))
            fillOval(ctx, CGRect(x: 15.4, y: 8.4, width: 5.2, height: 5.2), UIColor(rgb: 0x7E5C36))
            strokeOval(ctx, CGRect(x: 15.4, y: 8.4, width: 5.2, height: 5.2), UIColor(rgb: 0x0E0C08), width: 0.8)
            fillPolygon(ctx, [P(19.25, 8.83), P(5.75, 2.2), P(4.25, 4.8), P(16.75, 13.17)], UIColor(rgb: 0x7E5C36))
            strokePolygon(ctx, [P(19.25, 8.83), P(5.75, 2.2), P(4.25, 4.8), P(16.75, 13.17)], UIColor(rgb: 0x0E0C08), width: 0.8)
            fillPolygon(ctx, [P(16.75, 8.83), P(4.25, 17.2), P(5.75, 19.8), P(19.25, 13.17)], UIColor(rgb: 0x7E5C36))
            strokePolygon(ctx, [P(16.75, 8.83), P(4.25, 17.2), P(5.75, 19.8), P(19.25, 13.17)], UIColor(rgb: 0x0E0C08), width: 0.8)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.5))
    }

    // MARK: - projectileEmberBolt

    /// A gout of fire from the ember wand.
    static func projectileEmberBolt() -> Sprite {
        let image = render(CGSize(width: 18, height: 12)) { ctx in
            radialGradient(ctx, center: P(9, 6), radius: 9, inner: UIColor(rgb: 0xFFC24A, alpha: 0.75), outer: UIColor(rgb: 0xFFC24A, alpha: 0))
            fillPolygon(ctx, [P(1.5, 6.8), P(3.72, 7.1), P(6.06, 7.4), P(8.5, 7.7), P(11.06, 8), P(13.72, 8.3), P(16.5, 8.6), P(16.5, 3.4), P(13.72, 3.7), P(11.06, 4), P(8.5, 4.3), P(6.06, 4.6), P(3.72, 4.9), P(1.5, 5.2)], UIColor(rgb: 0xE2601A))
            strokePolygon(ctx, [P(1.5, 6.8), P(3.72, 7.1), P(6.06, 7.4), P(8.5, 7.7), P(11.06, 8), P(13.72, 8.3), P(16.5, 8.6), P(16.5, 3.4), P(13.72, 3.7), P(11.06, 4), P(8.5, 4.3), P(6.06, 4.6), P(3.72, 4.9), P(1.5, 5.2)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillOval(ctx, CGRect(x: 9.5, y: 3.2, width: 5.6, height: 5.6), UIColor(rgb: 0xEFA781))
            fillOval(ctx, CGRect(x: 10.3, y: 4.2, width: 2.4, height: 2.4), UIColor(rgb: 0xFFFFFF))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.5))
    }

    // MARK: - projectileFrostBolt

    /// A shard of ice from the rime wand.
    static func projectileFrostBolt() -> Sprite {
        let image = render(CGSize(width: 18, height: 12)) { ctx in
            radialGradient(ctx, center: P(9, 6), radius: 9, inner: UIColor(rgb: 0x3E7E9E, alpha: 0.75), outer: UIColor(rgb: 0x3E7E9E, alpha: 0))
            fillPolygon(ctx, [P(1.5, 6.8), P(3.72, 7.1), P(6.06, 7.4), P(8.5, 7.7), P(11.06, 8), P(13.72, 8.3), P(16.5, 8.6), P(16.5, 3.4), P(13.72, 3.7), P(11.06, 4), P(8.5, 4.3), P(6.06, 4.6), P(3.72, 4.9), P(1.5, 5.2)], UIColor(rgb: 0x8CD0E8))
            strokePolygon(ctx, [P(1.5, 6.8), P(3.72, 7.1), P(6.06, 7.4), P(8.5, 7.7), P(11.06, 8), P(13.72, 8.3), P(16.5, 8.6), P(16.5, 3.4), P(13.72, 3.7), P(11.06, 4), P(8.5, 4.3), P(6.06, 4.6), P(3.72, 4.9), P(1.5, 5.2)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillOval(ctx, CGRect(x: 9.5, y: 3.2, width: 5.6, height: 5.6), UIColor(rgb: 0xBFE5F2))
            fillOval(ctx, CGRect(x: 10.3, y: 4.2, width: 2.4, height: 2.4), UIColor(rgb: 0xFFFFFF))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.5))
    }

    // MARK: - projectileStormBolt

    /// A charge thrown from the storm wand.
    static func projectileStormBolt() -> Sprite {
        let image = render(CGSize(width: 18, height: 12)) { ctx in
            radialGradient(ctx, center: P(9, 6), radius: 9, inner: UIColor(rgb: 0xF2E4FF, alpha: 0.75), outer: UIColor(rgb: 0xF2E4FF, alpha: 0))
            fillPolygon(ctx, [P(1.5, 6.8), P(3.72, 7.1), P(6.06, 7.4), P(8.5, 7.7), P(11.06, 8), P(13.72, 8.3), P(16.5, 8.6), P(16.5, 3.4), P(13.72, 3.7), P(11.06, 4), P(8.5, 4.3), P(6.06, 4.6), P(3.72, 4.9), P(1.5, 5.2)], UIColor(rgb: 0xC9A6FF))
            strokePolygon(ctx, [P(1.5, 6.8), P(3.72, 7.1), P(6.06, 7.4), P(8.5, 7.7), P(11.06, 8), P(13.72, 8.3), P(16.5, 8.6), P(16.5, 3.4), P(13.72, 3.7), P(11.06, 4), P(8.5, 4.3), P(6.06, 4.6), P(3.72, 4.9), P(1.5, 5.2)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillOval(ctx, CGRect(x: 9.5, y: 3.2, width: 5.6, height: 5.6), UIColor(rgb: 0xE1CEFF))
            fillOval(ctx, CGRect(x: 10.3, y: 4.2, width: 2.4, height: 2.4), UIColor(rgb: 0xFFFFFF))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.5))
    }
}
