import UIKit

// Generated by tools/art/hero.py. Edit the Python and rerun it; do not edit
// this file by hand.

/// The hero, in layers: legs, cloak and head, once for each build and style.
/// Each draws into a context the caller owns and takes its colours from an
/// `ink`, so any combination the player picks is a few calls, not a sprite
/// baked in advance. The composition lives in PlaceholderArt+HeroFigure.swift.
extension PlaceholderArt {

    // MARK: - heroLegsLithe

    /// The lithe hero's legs and boots.
    static func heroLegsLithe(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(18.5, 45), P(22.5, 45), P(22.5, 58), P(18.5, 58)], UIColor(rgb: 0x2A2320))
        fillPolygon(ctx, [P(17.25, 55), P(23.75, 55), P(23.75, 60), P(17.25, 60)], UIColor(rgb: 0x1A1512))
        fillPolygon(ctx, [P(25.5, 45), P(29.5, 45), P(29.5, 58), P(25.5, 58)], UIColor(rgb: 0x2A2320))
        fillPolygon(ctx, [P(24.25, 55), P(30.75, 55), P(30.75, 60), P(24.25, 60)], UIColor(rgb: 0x1A1512))
    }

    // MARK: - heroLegsStandard

    /// The standard hero's legs and boots.
    static func heroLegsStandard(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(18, 45), P(22.5, 45), P(22.5, 58), P(18, 58)], UIColor(rgb: 0x2A2320))
        fillPolygon(ctx, [P(16.75, 55), P(23.75, 55), P(23.75, 60), P(16.75, 60)], UIColor(rgb: 0x1A1512))
        fillPolygon(ctx, [P(25.5, 45), P(30, 45), P(30, 58), P(25.5, 58)], UIColor(rgb: 0x2A2320))
        fillPolygon(ctx, [P(24.25, 55), P(31.25, 55), P(31.25, 60), P(24.25, 60)], UIColor(rgb: 0x1A1512))
    }

    // MARK: - heroLegsBroad

    /// The broad hero's legs and boots.
    static func heroLegsBroad(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(17, 45), P(22.5, 45), P(22.5, 58), P(17, 58)], UIColor(rgb: 0x2A2320))
        fillPolygon(ctx, [P(15.75, 55), P(23.75, 55), P(23.75, 60), P(15.75, 60)], UIColor(rgb: 0x1A1512))
        fillPolygon(ctx, [P(25.5, 45), P(31, 45), P(31, 58), P(25.5, 58)], UIColor(rgb: 0x2A2320))
        fillPolygon(ctx, [P(24.25, 55), P(32.25, 55), P(32.25, 60), P(24.25, 60)], UIColor(rgb: 0x1A1512))
    }

    // MARK: - heroCloakHoodedLithe

    /// A straight wayfarer's cloak on a lithe frame.
    static func heroCloakHoodedLithe(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 17), P(16, 25), P(12, 50), P(36, 50), P(32, 25)], ink.cloak())
        fillPolygon(ctx, [P(24, 17), P(32, 25), P(36, 50), P(25, 50)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 17), P(16, 25), P(12, 50), P(36, 50), P(32, 25)], UIColor(rgb: 0x0B0908), width: 1.2)
        stroke(ctx, from: P(14, 47.4), to: P(34, 47.4), ink.trim().withAlphaComponent(0.75), width: 1.3)
        fillPolygon(ctx, [P(17, 37), P(31, 37), P(31, 40), P(17, 40)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 36.5), P(25.5, 36.5), P(25.5, 40.5), P(22.5, 40.5)], ink.trim())
        fillOval(ctx, CGRect(x: 22.7, y: 25.2, width: 2.6, height: 2.6), ink.trim())
    }

    // MARK: - heroCloakMantleLithe

    /// A tunic under a short shoulder mantle on a lithe frame.
    static func heroCloakMantleLithe(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(17, 25), P(31, 25), P(34, 50), P(14, 50)], UIColor(rgb: 0x3B302B))
        fillPolygon(ctx, [P(24, 25), P(31, 25), P(34, 50), P(24, 50)], UIColor(rgb: 0x2E2521))
        strokePolygon(ctx, [P(17, 25), P(31, 25), P(34, 50), P(14, 50)], UIColor(rgb: 0x0B0908), width: 1.1)
        fillPolygon(ctx, [P(14, 47.6), P(34, 47.6), P(34, 50), P(14, 50)], ink.trim(0.7))
        fillPolygon(ctx, [P(17, 38.5), P(31, 38.5), P(31, 41.5), P(17, 41.5)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 38), P(25.5, 38), P(25.5, 42), P(22.5, 42)], ink.trim())
        fillPolygon(ctx, [P(24, 22), P(14.5, 25.5), P(11, 35), P(20.8, 37), P(27.2, 37), P(37, 35), P(33.5, 25.5)], ink.cloak())
        fillPolygon(ctx, [P(24, 22), P(33.5, 25.5), P(37, 35), P(27.2, 37), P(24, 36.4)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 22), P(14.5, 25.5), P(11, 35), P(20.8, 37), P(27.2, 37), P(37, 35), P(33.5, 25.5)], UIColor(rgb: 0x0B0908), width: 1.2)
        strokeCurve(ctx, [P(11.6, 34.2), P(20.8, 36.2), P(27.2, 36.2), P(36.4, 34.2)], ink.trim(), width: 1.2)
        fillOval(ctx, CGRect(x: 22.6, y: 23.1, width: 2.8, height: 2.8), ink.trim())
    }

    // MARK: - heroCloakLongCoatLithe

    /// A buttoned coat to the knee on a lithe frame.
    static func heroCloakLongCoatLithe(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 20), P(16, 25), P(13, 55), P(35, 55), P(32, 25)], ink.cloak())
        fillPolygon(ctx, [P(24, 20), P(32, 25), P(35, 55), P(24, 55)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 20), P(16, 25), P(13, 55), P(35, 55), P(32, 25)], UIColor(rgb: 0x0B0908), width: 1.2)
        fillPolygon(ctx, [P(24, 24), P(19.4, 26), P(22.4, 34)], ink.cloak(1.3))
        strokePolygon(ctx, [P(24, 24), P(19.4, 26), P(22.4, 34)], UIColor(rgb: 0x0B0908), width: 0.7)
        fillPolygon(ctx, [P(24, 24), P(28.6, 26), P(25.6, 34)], ink.cloak(1.05))
        strokePolygon(ctx, [P(24, 24), P(28.6, 26), P(25.6, 34)], UIColor(rgb: 0x0B0908), width: 0.7)
        stroke(ctx, from: P(24, 34), to: P(24, 55), ink.cloak(0.4), width: 1)
        fillOval(ctx, CGRect(x: 25.25, y: 35.05, width: 1.9, height: 1.9), ink.trim())
        fillOval(ctx, CGRect(x: 25.25, y: 40.05, width: 1.9, height: 1.9), ink.trim())
        fillOval(ctx, CGRect(x: 25.25, y: 45.05, width: 1.9, height: 1.9), ink.trim())
        fillPolygon(ctx, [P(17, 37), P(31, 37), P(31, 40), P(17, 40)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 36.5), P(25.5, 36.5), P(25.5, 40.5), P(22.5, 40.5)], ink.trim())
        fillPolygon(ctx, [P(14.5, 52.6), P(33.5, 52.6), P(33.5, 55), P(14.5, 55)], ink.trim(0.7))
    }

    // MARK: - heroCloakShroudLithe

    /// A ragged shroud with a torn hem on a lithe frame.
    static func heroCloakShroudLithe(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 17), P(16, 25), P(11, 56.4), P(14.71, 51.4), P(18.43, 56.4), P(22.14, 51.4), P(25.86, 56.4), P(29.57, 51.4), P(33.29, 56.4), P(37, 51.4), P(32, 25)], ink.cloak(0.92))
        fillPolygon(ctx, [P(12.8, 45), P(11, 56.4), P(14.71, 51.4), P(18.43, 56.4), P(22.14, 51.4), P(25.86, 56.4), P(29.57, 51.4), P(33.29, 56.4), P(37, 51.4), P(35.2, 45)], ink.cloak(0.6).withAlphaComponent(0.7))
        fillPolygon(ctx, [P(24, 17), P(32, 25), P(37, 51.4), P(25.86, 56.4)], ink.cloak(0.6).withAlphaComponent(0.55))
        strokePolygon(ctx, [P(24, 17), P(16, 25), P(11, 56.4), P(14.71, 51.4), P(18.43, 56.4), P(22.14, 51.4), P(25.86, 56.4), P(29.57, 51.4), P(33.29, 56.4), P(37, 51.4), P(32, 25)], UIColor(rgb: 0x0B0908), width: 1.2)
        stroke(ctx, from: P(14.71, 50.2), to: P(15.11, 44.9), ink.cloak(0.35), width: 0.8)
        stroke(ctx, from: P(22.14, 50.2), to: P(22.54, 44.9), ink.cloak(0.35), width: 0.8)
        stroke(ctx, from: P(29.57, 50.2), to: P(29.97, 44.9), ink.cloak(0.35), width: 0.8)
        fillPolygon(ctx, [P(17, 37), P(31, 37), P(31, 39.2), P(17, 39.2)], ink.trim(0.55))
        fillOval(ctx, CGRect(x: 25.9, y: 36.9, width: 3, height: 3), ink.trim(0.8))
        stroke(ctx, from: P(27.4, 39), to: P(29, 44), ink.trim(0.55), width: 1)
    }

    // MARK: - heroCloakPilgrimLithe

    /// A long cloak, a yoke and a high collar on a lithe frame.
    static func heroCloakPilgrimLithe(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 17), P(16, 25), P(12, 50), P(36, 50), P(32, 25)], ink.cloak())
        fillPolygon(ctx, [P(24, 17), P(32, 25), P(36, 50), P(25, 50)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 17), P(16, 25), P(12, 50), P(36, 50), P(32, 25)], UIColor(rgb: 0x0B0908), width: 1.2)
        fillPolygon(ctx, [P(17, 38.5), P(31, 38.5), P(31, 41.5), P(17, 41.5)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 38), P(25.5, 38), P(25.5, 42), P(22.5, 42)], ink.trim())
        fillPolygon(ctx, [P(24, 22), P(12, 26.5), P(11, 36), P(37, 36), P(36, 26.5)], ink.cloak(1.2))
        fillPolygon(ctx, [P(24, 22), P(36, 26.5), P(37, 36), P(24, 36)], ink.cloak(0.95))
        strokePolygon(ctx, [P(24, 22), P(12, 26.5), P(11, 36), P(37, 36), P(36, 26.5)], UIColor(rgb: 0x0B0908), width: 1.2)
        stroke(ctx, from: P(11.6, 34.6), to: P(36.4, 34.6), ink.trim(), width: 1.3)
        fillPolygon(ctx, [P(21, 18), P(15.5, 13.5), P(14.5, 25.5), P(21, 26.5)], ink.cloak(0.9))
        strokePolygon(ctx, [P(21, 18), P(15.5, 13.5), P(14.5, 25.5), P(21, 26.5)], UIColor(rgb: 0x0B0908), width: 1)
        fillPolygon(ctx, [P(27, 18), P(32.5, 13.5), P(33.5, 25.5), P(27, 26.5)], ink.cloak(0.62))
        strokePolygon(ctx, [P(27, 18), P(32.5, 13.5), P(33.5, 25.5), P(27, 26.5)], UIColor(rgb: 0x0B0908), width: 1)
        stroke(ctx, from: P(15.5, 15), to: P(15, 24), ink.trim(), width: 0.9)
        stroke(ctx, from: P(32.5, 15), to: P(33, 24), ink.trim(), width: 0.9)
    }

    // MARK: - heroCloakHoodedStandard

    /// A straight wayfarer's cloak on a standard frame.
    static func heroCloakHoodedStandard(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 20), P(14, 28), P(10, 51), P(38, 51), P(34, 28)], ink.cloak())
        fillPolygon(ctx, [P(24, 20), P(34, 28), P(38, 51), P(25, 51)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 20), P(14, 28), P(10, 51), P(38, 51), P(34, 28)], UIColor(rgb: 0x0B0908), width: 1.2)
        stroke(ctx, from: P(12, 48.4), to: P(36, 48.4), ink.trim().withAlphaComponent(0.75), width: 1.3)
        fillPolygon(ctx, [P(15, 40), P(33, 40), P(33, 43), P(15, 43)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 39.5), P(25.5, 39.5), P(25.5, 43.5), P(22.5, 43.5)], ink.trim())
        fillOval(ctx, CGRect(x: 22.7, y: 28.2, width: 2.6, height: 2.6), ink.trim())
    }

    // MARK: - heroCloakMantleStandard

    /// A tunic under a short shoulder mantle on a standard frame.
    static func heroCloakMantleStandard(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(15, 28), P(33, 28), P(36, 51), P(12, 51)], UIColor(rgb: 0x3B302B))
        fillPolygon(ctx, [P(24, 28), P(33, 28), P(36, 51), P(24, 51)], UIColor(rgb: 0x2E2521))
        strokePolygon(ctx, [P(15, 28), P(33, 28), P(36, 51), P(12, 51)], UIColor(rgb: 0x0B0908), width: 1.1)
        fillPolygon(ctx, [P(12, 48.6), P(36, 48.6), P(36, 51), P(12, 51)], ink.trim(0.7))
        fillPolygon(ctx, [P(15, 41.5), P(33, 41.5), P(33, 44.5), P(15, 44.5)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 41), P(25.5, 41), P(25.5, 45), P(22.5, 45)], ink.trim())
        fillPolygon(ctx, [P(24, 25), P(12.5, 28.5), P(9, 38), P(20, 40), P(28, 40), P(39, 38), P(35.5, 28.5)], ink.cloak())
        fillPolygon(ctx, [P(24, 25), P(35.5, 28.5), P(39, 38), P(28, 40), P(24, 39.4)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 25), P(12.5, 28.5), P(9, 38), P(20, 40), P(28, 40), P(39, 38), P(35.5, 28.5)], UIColor(rgb: 0x0B0908), width: 1.2)
        strokeCurve(ctx, [P(9.6, 37.2), P(20, 39.2), P(28, 39.2), P(38.4, 37.2)], ink.trim(), width: 1.2)
        fillOval(ctx, CGRect(x: 22.6, y: 26.1, width: 2.8, height: 2.8), ink.trim())
    }

    // MARK: - heroCloakLongCoatStandard

    /// A buttoned coat to the knee on a standard frame.
    static func heroCloakLongCoatStandard(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 23), P(14, 28), P(11, 56), P(37, 56), P(34, 28)], ink.cloak())
        fillPolygon(ctx, [P(24, 23), P(34, 28), P(37, 56), P(24, 56)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 23), P(14, 28), P(11, 56), P(37, 56), P(34, 28)], UIColor(rgb: 0x0B0908), width: 1.2)
        fillPolygon(ctx, [P(24, 27), P(19.4, 29), P(22.4, 37)], ink.cloak(1.3))
        strokePolygon(ctx, [P(24, 27), P(19.4, 29), P(22.4, 37)], UIColor(rgb: 0x0B0908), width: 0.7)
        fillPolygon(ctx, [P(24, 27), P(28.6, 29), P(25.6, 37)], ink.cloak(1.05))
        strokePolygon(ctx, [P(24, 27), P(28.6, 29), P(25.6, 37)], UIColor(rgb: 0x0B0908), width: 0.7)
        stroke(ctx, from: P(24, 37), to: P(24, 56), ink.cloak(0.4), width: 1)
        fillOval(ctx, CGRect(x: 25.25, y: 38.05, width: 1.9, height: 1.9), ink.trim())
        fillOval(ctx, CGRect(x: 25.25, y: 43.05, width: 1.9, height: 1.9), ink.trim())
        fillOval(ctx, CGRect(x: 25.25, y: 48.05, width: 1.9, height: 1.9), ink.trim())
        fillPolygon(ctx, [P(15, 40), P(33, 40), P(33, 43), P(15, 43)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 39.5), P(25.5, 39.5), P(25.5, 43.5), P(22.5, 43.5)], ink.trim())
        fillPolygon(ctx, [P(12.5, 53.6), P(35.5, 53.6), P(35.5, 56), P(12.5, 56)], ink.trim(0.7))
    }

    // MARK: - heroCloakShroudStandard

    /// A ragged shroud with a torn hem on a standard frame.
    static func heroCloakShroudStandard(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 20), P(14, 28), P(9, 57.4), P(13.29, 52.4), P(17.57, 57.4), P(21.86, 52.4), P(26.14, 57.4), P(30.43, 52.4), P(34.71, 57.4), P(39, 52.4), P(34, 28)], ink.cloak(0.92))
        fillPolygon(ctx, [P(10.87, 46), P(9, 57.4), P(13.29, 52.4), P(17.57, 57.4), P(21.86, 52.4), P(26.14, 57.4), P(30.43, 52.4), P(34.71, 57.4), P(39, 52.4), P(37.13, 46)], ink.cloak(0.6).withAlphaComponent(0.7))
        fillPolygon(ctx, [P(24, 20), P(34, 28), P(39, 52.4), P(26.14, 57.4)], ink.cloak(0.6).withAlphaComponent(0.55))
        strokePolygon(ctx, [P(24, 20), P(14, 28), P(9, 57.4), P(13.29, 52.4), P(17.57, 57.4), P(21.86, 52.4), P(26.14, 57.4), P(30.43, 52.4), P(34.71, 57.4), P(39, 52.4), P(34, 28)], UIColor(rgb: 0x0B0908), width: 1.2)
        stroke(ctx, from: P(13.29, 51.2), to: P(13.69, 45.9), ink.cloak(0.35), width: 0.8)
        stroke(ctx, from: P(21.86, 51.2), to: P(22.26, 45.9), ink.cloak(0.35), width: 0.8)
        stroke(ctx, from: P(30.43, 51.2), to: P(30.83, 45.9), ink.cloak(0.35), width: 0.8)
        fillPolygon(ctx, [P(15, 40), P(33, 40), P(33, 42.2), P(15, 42.2)], ink.trim(0.55))
        fillOval(ctx, CGRect(x: 25.9, y: 39.9, width: 3, height: 3), ink.trim(0.8))
        stroke(ctx, from: P(27.4, 42), to: P(29, 47), ink.trim(0.55), width: 1)
    }

    // MARK: - heroCloakPilgrimStandard

    /// A long cloak, a yoke and a high collar on a standard frame.
    static func heroCloakPilgrimStandard(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 20), P(14, 28), P(10, 51), P(38, 51), P(34, 28)], ink.cloak())
        fillPolygon(ctx, [P(24, 20), P(34, 28), P(38, 51), P(25, 51)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 20), P(14, 28), P(10, 51), P(38, 51), P(34, 28)], UIColor(rgb: 0x0B0908), width: 1.2)
        fillPolygon(ctx, [P(15, 41.5), P(33, 41.5), P(33, 44.5), P(15, 44.5)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 41), P(25.5, 41), P(25.5, 45), P(22.5, 45)], ink.trim())
        fillPolygon(ctx, [P(24, 25), P(10, 29.5), P(9, 39), P(39, 39), P(38, 29.5)], ink.cloak(1.2))
        fillPolygon(ctx, [P(24, 25), P(38, 29.5), P(39, 39), P(24, 39)], ink.cloak(0.95))
        strokePolygon(ctx, [P(24, 25), P(10, 29.5), P(9, 39), P(39, 39), P(38, 29.5)], UIColor(rgb: 0x0B0908), width: 1.2)
        stroke(ctx, from: P(9.6, 37.6), to: P(38.4, 37.6), ink.trim(), width: 1.3)
        fillPolygon(ctx, [P(21, 21), P(15.5, 16.5), P(14.5, 28.5), P(21, 29.5)], ink.cloak(0.9))
        strokePolygon(ctx, [P(21, 21), P(15.5, 16.5), P(14.5, 28.5), P(21, 29.5)], UIColor(rgb: 0x0B0908), width: 1)
        fillPolygon(ctx, [P(27, 21), P(32.5, 16.5), P(33.5, 28.5), P(27, 29.5)], ink.cloak(0.62))
        strokePolygon(ctx, [P(27, 21), P(32.5, 16.5), P(33.5, 28.5), P(27, 29.5)], UIColor(rgb: 0x0B0908), width: 1)
        stroke(ctx, from: P(15.5, 18), to: P(15, 27), ink.trim(), width: 0.9)
        stroke(ctx, from: P(32.5, 18), to: P(33, 27), ink.trim(), width: 0.9)
    }

    // MARK: - heroCloakHoodedBroad

    /// A straight wayfarer's cloak on a broad frame.
    static func heroCloakHoodedBroad(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 21), P(11, 29), P(7, 51), P(41, 51), P(37, 29)], ink.cloak())
        fillPolygon(ctx, [P(24, 21), P(37, 29), P(41, 51), P(25, 51)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 21), P(11, 29), P(7, 51), P(41, 51), P(37, 29)], UIColor(rgb: 0x0B0908), width: 1.2)
        stroke(ctx, from: P(9, 48.4), to: P(39, 48.4), ink.trim().withAlphaComponent(0.75), width: 1.3)
        fillPolygon(ctx, [P(12, 41), P(36, 41), P(36, 44), P(12, 44)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 40.5), P(25.5, 40.5), P(25.5, 44.5), P(22.5, 44.5)], ink.trim())
        fillOval(ctx, CGRect(x: 22.7, y: 29.2, width: 2.6, height: 2.6), ink.trim())
    }

    // MARK: - heroCloakMantleBroad

    /// A tunic under a short shoulder mantle on a broad frame.
    static func heroCloakMantleBroad(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(12, 29), P(36, 29), P(39, 51), P(9, 51)], UIColor(rgb: 0x3B302B))
        fillPolygon(ctx, [P(24, 29), P(36, 29), P(39, 51), P(24, 51)], UIColor(rgb: 0x2E2521))
        strokePolygon(ctx, [P(12, 29), P(36, 29), P(39, 51), P(9, 51)], UIColor(rgb: 0x0B0908), width: 1.1)
        fillPolygon(ctx, [P(9, 48.6), P(39, 48.6), P(39, 51), P(9, 51)], ink.trim(0.7))
        fillPolygon(ctx, [P(12, 42.5), P(36, 42.5), P(36, 45.5), P(12, 45.5)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 42), P(25.5, 42), P(25.5, 46), P(22.5, 46)], ink.trim())
        fillPolygon(ctx, [P(24, 26), P(9.5, 29.5), P(6, 39), P(18.8, 41), P(29.2, 41), P(42, 39), P(38.5, 29.5)], ink.cloak())
        fillPolygon(ctx, [P(24, 26), P(38.5, 29.5), P(42, 39), P(29.2, 41), P(24, 40.4)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 26), P(9.5, 29.5), P(6, 39), P(18.8, 41), P(29.2, 41), P(42, 39), P(38.5, 29.5)], UIColor(rgb: 0x0B0908), width: 1.2)
        strokeCurve(ctx, [P(6.6, 38.2), P(18.8, 40.2), P(29.2, 40.2), P(41.4, 38.2)], ink.trim(), width: 1.2)
        fillOval(ctx, CGRect(x: 22.6, y: 27.1, width: 2.8, height: 2.8), ink.trim())
    }

    // MARK: - heroCloakLongCoatBroad

    /// A buttoned coat to the knee on a broad frame.
    static func heroCloakLongCoatBroad(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 24), P(11, 29), P(8, 56), P(40, 56), P(37, 29)], ink.cloak())
        fillPolygon(ctx, [P(24, 24), P(37, 29), P(40, 56), P(24, 56)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 24), P(11, 29), P(8, 56), P(40, 56), P(37, 29)], UIColor(rgb: 0x0B0908), width: 1.2)
        fillPolygon(ctx, [P(24, 28), P(19.4, 30), P(22.4, 38)], ink.cloak(1.3))
        strokePolygon(ctx, [P(24, 28), P(19.4, 30), P(22.4, 38)], UIColor(rgb: 0x0B0908), width: 0.7)
        fillPolygon(ctx, [P(24, 28), P(28.6, 30), P(25.6, 38)], ink.cloak(1.05))
        strokePolygon(ctx, [P(24, 28), P(28.6, 30), P(25.6, 38)], UIColor(rgb: 0x0B0908), width: 0.7)
        stroke(ctx, from: P(24, 38), to: P(24, 56), ink.cloak(0.4), width: 1)
        fillOval(ctx, CGRect(x: 25.25, y: 39.05, width: 1.9, height: 1.9), ink.trim())
        fillOval(ctx, CGRect(x: 25.25, y: 44.05, width: 1.9, height: 1.9), ink.trim())
        fillOval(ctx, CGRect(x: 25.25, y: 49.05, width: 1.9, height: 1.9), ink.trim())
        fillPolygon(ctx, [P(12, 41), P(36, 41), P(36, 44), P(12, 44)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 40.5), P(25.5, 40.5), P(25.5, 44.5), P(22.5, 44.5)], ink.trim())
        fillPolygon(ctx, [P(9.5, 53.6), P(38.5, 53.6), P(38.5, 56), P(9.5, 56)], ink.trim(0.7))
    }

    // MARK: - heroCloakShroudBroad

    /// A ragged shroud with a torn hem on a broad frame.
    static func heroCloakShroudBroad(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 21), P(11, 29), P(6, 57.4), P(11.14, 52.4), P(16.29, 57.4), P(21.43, 52.4), P(26.57, 57.4), P(31.71, 52.4), P(36.86, 57.4), P(42, 52.4), P(37, 29)], ink.cloak(0.92))
        fillPolygon(ctx, [P(7.91, 46), P(6, 57.4), P(11.14, 52.4), P(16.29, 57.4), P(21.43, 52.4), P(26.57, 57.4), P(31.71, 52.4), P(36.86, 57.4), P(42, 52.4), P(40.09, 46)], ink.cloak(0.6).withAlphaComponent(0.7))
        fillPolygon(ctx, [P(24, 21), P(37, 29), P(42, 52.4), P(26.57, 57.4)], ink.cloak(0.6).withAlphaComponent(0.55))
        strokePolygon(ctx, [P(24, 21), P(11, 29), P(6, 57.4), P(11.14, 52.4), P(16.29, 57.4), P(21.43, 52.4), P(26.57, 57.4), P(31.71, 52.4), P(36.86, 57.4), P(42, 52.4), P(37, 29)], UIColor(rgb: 0x0B0908), width: 1.2)
        stroke(ctx, from: P(11.14, 51.2), to: P(11.54, 45.9), ink.cloak(0.35), width: 0.8)
        stroke(ctx, from: P(21.43, 51.2), to: P(21.83, 45.9), ink.cloak(0.35), width: 0.8)
        stroke(ctx, from: P(31.71, 51.2), to: P(32.11, 45.9), ink.cloak(0.35), width: 0.8)
        fillPolygon(ctx, [P(12, 41), P(36, 41), P(36, 43.2), P(12, 43.2)], ink.trim(0.55))
        fillOval(ctx, CGRect(x: 25.9, y: 40.9, width: 3, height: 3), ink.trim(0.8))
        stroke(ctx, from: P(27.4, 43), to: P(29, 48), ink.trim(0.55), width: 1)
    }

    // MARK: - heroCloakPilgrimBroad

    /// A long cloak, a yoke and a high collar on a broad frame.
    static func heroCloakPilgrimBroad(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(24, 21), P(11, 29), P(7, 51), P(41, 51), P(37, 29)], ink.cloak())
        fillPolygon(ctx, [P(24, 21), P(37, 29), P(41, 51), P(25, 51)], ink.cloak(0.75))
        strokePolygon(ctx, [P(24, 21), P(11, 29), P(7, 51), P(41, 51), P(37, 29)], UIColor(rgb: 0x0B0908), width: 1.2)
        fillPolygon(ctx, [P(12, 42.5), P(36, 42.5), P(36, 45.5), P(12, 45.5)], UIColor(rgb: 0x3A2A1C))
        fillPolygon(ctx, [P(22.5, 42), P(25.5, 42), P(25.5, 46), P(22.5, 46)], ink.trim())
        fillPolygon(ctx, [P(24, 26), P(7, 30.5), P(6, 40), P(42, 40), P(41, 30.5)], ink.cloak(1.2))
        fillPolygon(ctx, [P(24, 26), P(41, 30.5), P(42, 40), P(24, 40)], ink.cloak(0.95))
        strokePolygon(ctx, [P(24, 26), P(7, 30.5), P(6, 40), P(42, 40), P(41, 30.5)], UIColor(rgb: 0x0B0908), width: 1.2)
        stroke(ctx, from: P(6.6, 38.6), to: P(41.4, 38.6), ink.trim(), width: 1.3)
        fillPolygon(ctx, [P(21, 22), P(15.5, 17.5), P(14.5, 29.5), P(21, 30.5)], ink.cloak(0.9))
        strokePolygon(ctx, [P(21, 22), P(15.5, 17.5), P(14.5, 29.5), P(21, 30.5)], UIColor(rgb: 0x0B0908), width: 1)
        fillPolygon(ctx, [P(27, 22), P(32.5, 17.5), P(33.5, 29.5), P(27, 30.5)], ink.cloak(0.62))
        strokePolygon(ctx, [P(27, 22), P(32.5, 17.5), P(33.5, 29.5), P(27, 30.5)], UIColor(rgb: 0x0B0908), width: 1)
        stroke(ctx, from: P(15.5, 19), to: P(15, 28), ink.trim(), width: 0.9)
        stroke(ctx, from: P(32.5, 19), to: P(33, 28), ink.trim(), width: 0.9)
    }

    // MARK: - heroHeadHoodLithe

    /// A deep hood on a lithe frame, the face left in shadow.
    static func heroHeadHoodLithe(_ ctx: CGContext, _ ink: HeroInk) {
        fillOval(ctx, CGRect(x: 15.5, y: 7, width: 17, height: 18), ink.cloak(0.7))
        strokeOval(ctx, CGRect(x: 15.5, y: 7, width: 17, height: 18), UIColor(rgb: 0x0B0908), width: 1.2)
        fillOval(ctx, CGRect(x: 19.5, y: 13.66, width: 9, height: 8.46), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 20.96, y: 16.72, width: 2, height: 1.6), ink.eyes())
        fillOval(ctx, CGRect(x: 25.25, y: 16.72, width: 2, height: 1.6), ink.eyes())
        strokeCurve(ctx, [P(16.93, 14.88), P(18.21, 11.79), P(20.36, 9.84), P(22.88, 8.93)], ink.cloak(1.7), width: 1)
    }

    // MARK: - heroHeadCowlLithe

    /// A hood with a cloth drawn across the mouth on a lithe frame.
    static func heroHeadCowlLithe(_ ctx: CGContext, _ ink: HeroInk) {
        fillOval(ctx, CGRect(x: 15.5, y: 7, width: 17, height: 18), ink.cloak(0.7))
        strokeOval(ctx, CGRect(x: 15.5, y: 7, width: 17, height: 18), UIColor(rgb: 0x0B0908), width: 1.2)
        fillOval(ctx, CGRect(x: 19.5, y: 13.66, width: 9, height: 8.46), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 20.96, y: 16.72, width: 2, height: 1.6), ink.eyes())
        fillOval(ctx, CGRect(x: 25.25, y: 16.72, width: 2, height: 1.6), ink.eyes())
        strokeCurve(ctx, [P(16.93, 14.88), P(18.21, 11.79), P(20.36, 9.84), P(22.88, 8.93)], ink.cloak(1.7), width: 1)
        fillPolygon(ctx, [P(19.9, 18.91), P(24, 17.11), P(28.1, 18.91), P(27.5, 22.12), P(24, 23.72), P(20.5, 22.12)], ink.trim(0.55))
        strokePolygon(ctx, [P(19.9, 18.91), P(24, 17.11), P(28.1, 18.91), P(27.5, 22.12), P(24, 23.72), P(20.5, 22.12)], UIColor(rgb: 0x0B0908), width: 0.8)
        stroke(ctx, from: P(20.7, 20.71), to: P(27.3, 21.31), ink.trim(0.35), width: 0.7)
    }

    // MARK: - heroHeadBareLithe

    /// A bare head on a lithe frame: skin, hair and open eyes.
    static func heroHeadBareLithe(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(21.9, 20.5), P(26.1, 20.5), P(26.1, 26), P(21.9, 26)], ink.skin(0.66))
        fillOval(ctx, CGRect(x: 16.4, y: 5.5, width: 15.2, height: 15), ink.hair(0.8))
        strokeOval(ctx, CGRect(x: 16.4, y: 5.5, width: 15.2, height: 15), UIColor(rgb: 0x0B0908), width: 1)
        fillOval(ctx, CGRect(x: 18, y: 8, width: 12, height: 13.5), ink.skin())
        strokeOval(ctx, CGRect(x: 18, y: 8, width: 12, height: 13.5), UIColor(rgb: 0x0B0908), width: 1)
        fillSmooth(ctx, [P(17, 16.5), P(17.4, 10.5), P(20.5, 6.6), P(27.5, 6.6), P(30.6, 10.5), P(31, 16.5), P(29.4, 13.2), P(25.5, 11), P(21, 12.6), P(18.8, 14.2)], ink.hair())
        strokeSmooth(ctx, [P(17, 16.5), P(17.4, 10.5), P(20.5, 6.6), P(27.5, 6.6), P(30.6, 10.5), P(31, 16.5), P(29.4, 13.2), P(25.5, 11), P(21, 12.6), P(18.8, 14.2)], UIColor(rgb: 0x0B0908), width: 0.8)
        fillOval(ctx, CGRect(x: 20.5, y: 14.5, width: 2.2, height: 2.2), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 25.3, y: 14.5, width: 2.2, height: 2.2), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 20.85, y: 14.85, width: 1.5, height: 1.5), ink.eyes())
        fillOval(ctx, CGRect(x: 25.65, y: 14.85, width: 1.5, height: 1.5), ink.eyes())
        stroke(ctx, from: P(20.2, 13.6), to: P(22.7, 14.1), ink.hair(0.7), width: 0.8)
        stroke(ctx, from: P(25.3, 14.1), to: P(27.8, 13.6), ink.hair(0.7), width: 0.8)
        stroke(ctx, from: P(22.8, 19.4), to: P(25.2, 19.4), ink.skin(0.55), width: 0.7)
    }

    // MARK: - heroHeadHelmLithe

    /// An open iron helm on a lithe frame, with a crest and lit eyes.
    static func heroHeadHelmLithe(_ ctx: CGContext, _ ink: HeroInk) {
        fillOval(ctx, CGRect(x: 16.2, y: 6, width: 15.6, height: 15), UIColor(rgb: 0x8A9098))
        strokeOval(ctx, CGRect(x: 16.2, y: 6, width: 15.6, height: 15), UIColor(rgb: 0x0B0908), width: 1.2)
        fillPolygon(ctx, [P(25, 6.4), P(31, 11), P(31.6, 16), P(25, 20)], ink.cloak(0.2).withAlphaComponent(0.18))
        fillPolygon(ctx, [P(19.2, 12.4), P(28.8, 12.4), P(27.8, 20.4), P(24, 22), P(20.2, 20.4)], UIColor(rgb: 0x120D0C))
        fillPolygon(ctx, [P(16.6, 15), P(17.4, 20.6), P(21, 22.4), P(21.4, 16.6)], UIColor(rgb: 0x6E747C))
        strokePolygon(ctx, [P(16.6, 15), P(17.4, 20.6), P(21, 22.4), P(21.4, 16.6)], UIColor(rgb: 0x0B0908), width: 0.9)
        fillPolygon(ctx, [P(31.4, 15), P(30.6, 20.6), P(27, 22.4), P(26.6, 16.6)], UIColor(rgb: 0x5C626A))
        strokePolygon(ctx, [P(31.4, 15), P(30.6, 20.6), P(27, 22.4), P(26.6, 16.6)], UIColor(rgb: 0x0B0908), width: 0.9)
        fillPolygon(ctx, [P(16.4, 11.4), P(31.6, 11.4), P(31.6, 13.3), P(16.4, 13.3)], UIColor(rgb: 0x6E747C))
        strokePolygon(ctx, [P(16.4, 11.4), P(31.6, 11.4), P(31.6, 13.3), P(16.4, 13.3)], UIColor(rgb: 0x0B0908), width: 0.6)
        fillPolygon(ctx, [P(23.1, 12), P(24.9, 12), P(24.9, 20.6), P(23.1, 20.6)], UIColor(rgb: 0x8A9098))
        strokePolygon(ctx, [P(23.1, 12), P(24.9, 12), P(24.9, 20.6), P(23.1, 20.6)], UIColor(rgb: 0x0B0908), width: 0.6)
        fillOval(ctx, CGRect(x: 19.6, y: 14.4, width: 2.2, height: 1.6), ink.eyes())
        fillOval(ctx, CGRect(x: 26.2, y: 14.4, width: 2.2, height: 1.6), ink.eyes())
        strokeCurve(ctx, [P(18.4, 10.6), P(19.4, 8), P(22.4, 6.8)], UIColor(rgb: 0xC9CFD6), width: 1)
        fillPolygon(ctx, [P(22.1, 6.4), P(24, 0.5), P(25.9, 6.4)], ink.trim())
        strokePolygon(ctx, [P(22.1, 6.4), P(24, 0.5), P(25.9, 6.4)], UIColor(rgb: 0x0B0908), width: 0.8)
    }

    // MARK: - heroHeadHoodStandard

    /// A deep hood on a standard frame, the face left in shadow.
    static func heroHeadHoodStandard(_ ctx: CGContext, _ ink: HeroInk) {
        fillOval(ctx, CGRect(x: 14.5, y: 9, width: 19, height: 19), ink.cloak(0.7))
        strokeOval(ctx, CGRect(x: 14.5, y: 9, width: 19, height: 19), UIColor(rgb: 0x0B0908), width: 1.2)
        fillOval(ctx, CGRect(x: 18.5, y: 16.03, width: 11, height: 8.93), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 20.6, y: 19.26, width: 2, height: 1.6), ink.eyes())
        fillOval(ctx, CGRect(x: 25.4, y: 19.26, width: 2, height: 1.6), ink.eyes())
        strokeCurve(ctx, [P(16.1, 17.25), P(17.53, 13.8), P(19.93, 11.61), P(22.75, 10.6)], ink.cloak(1.7), width: 1)
    }

    // MARK: - heroHeadCowlStandard

    /// A hood with a cloth drawn across the mouth on a standard frame.
    static func heroHeadCowlStandard(_ ctx: CGContext, _ ink: HeroInk) {
        fillOval(ctx, CGRect(x: 14.5, y: 9, width: 19, height: 19), ink.cloak(0.7))
        strokeOval(ctx, CGRect(x: 14.5, y: 9, width: 19, height: 19), UIColor(rgb: 0x0B0908), width: 1.2)
        fillOval(ctx, CGRect(x: 18.5, y: 16.03, width: 11, height: 8.93), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 20.6, y: 19.26, width: 2, height: 1.6), ink.eyes())
        fillOval(ctx, CGRect(x: 25.4, y: 19.26, width: 2, height: 1.6), ink.eyes())
        strokeCurve(ctx, [P(16.1, 17.25), P(17.53, 13.8), P(19.93, 11.61), P(22.75, 10.6)], ink.cloak(1.7), width: 1)
        fillPolygon(ctx, [P(18.9, 21.54), P(24, 19.74), P(29.1, 21.54), P(28.5, 24.96), P(24, 26.56), P(19.5, 24.96)], ink.trim(0.55))
        strokePolygon(ctx, [P(18.9, 21.54), P(24, 19.74), P(29.1, 21.54), P(28.5, 24.96), P(24, 26.56), P(19.5, 24.96)], UIColor(rgb: 0x0B0908), width: 0.8)
        stroke(ctx, from: P(19.7, 23.34), to: P(28.3, 23.94), ink.trim(0.35), width: 0.7)
    }

    // MARK: - heroHeadBareStandard

    /// A bare head on a standard frame: skin, hair and open eyes.
    static func heroHeadBareStandard(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(21.9, 23.5), P(26.1, 23.5), P(26.1, 29), P(21.9, 29)], ink.skin(0.66))
        fillOval(ctx, CGRect(x: 16.4, y: 8.5, width: 15.2, height: 15), ink.hair(0.8))
        strokeOval(ctx, CGRect(x: 16.4, y: 8.5, width: 15.2, height: 15), UIColor(rgb: 0x0B0908), width: 1)
        fillOval(ctx, CGRect(x: 18, y: 11, width: 12, height: 13.5), ink.skin())
        strokeOval(ctx, CGRect(x: 18, y: 11, width: 12, height: 13.5), UIColor(rgb: 0x0B0908), width: 1)
        fillSmooth(ctx, [P(17, 19.5), P(17.4, 13.5), P(20.5, 9.6), P(27.5, 9.6), P(30.6, 13.5), P(31, 19.5), P(29.4, 16.2), P(25.5, 14), P(21, 15.6), P(18.8, 17.2)], ink.hair())
        strokeSmooth(ctx, [P(17, 19.5), P(17.4, 13.5), P(20.5, 9.6), P(27.5, 9.6), P(30.6, 13.5), P(31, 19.5), P(29.4, 16.2), P(25.5, 14), P(21, 15.6), P(18.8, 17.2)], UIColor(rgb: 0x0B0908), width: 0.8)
        fillOval(ctx, CGRect(x: 20.5, y: 17.5, width: 2.2, height: 2.2), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 25.3, y: 17.5, width: 2.2, height: 2.2), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 20.85, y: 17.85, width: 1.5, height: 1.5), ink.eyes())
        fillOval(ctx, CGRect(x: 25.65, y: 17.85, width: 1.5, height: 1.5), ink.eyes())
        stroke(ctx, from: P(20.2, 16.6), to: P(22.7, 17.1), ink.hair(0.7), width: 0.8)
        stroke(ctx, from: P(25.3, 17.1), to: P(27.8, 16.6), ink.hair(0.7), width: 0.8)
        stroke(ctx, from: P(22.8, 22.4), to: P(25.2, 22.4), ink.skin(0.55), width: 0.7)
    }

    // MARK: - heroHeadHelmStandard

    /// An open iron helm on a standard frame, with a crest and lit eyes.
    static func heroHeadHelmStandard(_ ctx: CGContext, _ ink: HeroInk) {
        fillOval(ctx, CGRect(x: 16.2, y: 9, width: 15.6, height: 15), UIColor(rgb: 0x8A9098))
        strokeOval(ctx, CGRect(x: 16.2, y: 9, width: 15.6, height: 15), UIColor(rgb: 0x0B0908), width: 1.2)
        fillPolygon(ctx, [P(25, 9.4), P(31, 14), P(31.6, 19), P(25, 23)], ink.cloak(0.2).withAlphaComponent(0.18))
        fillPolygon(ctx, [P(19.2, 15.4), P(28.8, 15.4), P(27.8, 23.4), P(24, 25), P(20.2, 23.4)], UIColor(rgb: 0x120D0C))
        fillPolygon(ctx, [P(16.6, 18), P(17.4, 23.6), P(21, 25.4), P(21.4, 19.6)], UIColor(rgb: 0x6E747C))
        strokePolygon(ctx, [P(16.6, 18), P(17.4, 23.6), P(21, 25.4), P(21.4, 19.6)], UIColor(rgb: 0x0B0908), width: 0.9)
        fillPolygon(ctx, [P(31.4, 18), P(30.6, 23.6), P(27, 25.4), P(26.6, 19.6)], UIColor(rgb: 0x5C626A))
        strokePolygon(ctx, [P(31.4, 18), P(30.6, 23.6), P(27, 25.4), P(26.6, 19.6)], UIColor(rgb: 0x0B0908), width: 0.9)
        fillPolygon(ctx, [P(16.4, 14.4), P(31.6, 14.4), P(31.6, 16.3), P(16.4, 16.3)], UIColor(rgb: 0x6E747C))
        strokePolygon(ctx, [P(16.4, 14.4), P(31.6, 14.4), P(31.6, 16.3), P(16.4, 16.3)], UIColor(rgb: 0x0B0908), width: 0.6)
        fillPolygon(ctx, [P(23.1, 15), P(24.9, 15), P(24.9, 23.6), P(23.1, 23.6)], UIColor(rgb: 0x8A9098))
        strokePolygon(ctx, [P(23.1, 15), P(24.9, 15), P(24.9, 23.6), P(23.1, 23.6)], UIColor(rgb: 0x0B0908), width: 0.6)
        fillOval(ctx, CGRect(x: 19.6, y: 17.4, width: 2.2, height: 1.6), ink.eyes())
        fillOval(ctx, CGRect(x: 26.2, y: 17.4, width: 2.2, height: 1.6), ink.eyes())
        strokeCurve(ctx, [P(18.4, 13.6), P(19.4, 11), P(22.4, 9.8)], UIColor(rgb: 0xC9CFD6), width: 1)
        fillPolygon(ctx, [P(22.1, 9.4), P(24, 3.5), P(25.9, 9.4)], ink.trim())
        strokePolygon(ctx, [P(22.1, 9.4), P(24, 3.5), P(25.9, 9.4)], UIColor(rgb: 0x0B0908), width: 0.8)
    }

    // MARK: - heroHeadHoodBroad

    /// A deep hood on a broad frame, the face left in shadow.
    static func heroHeadHoodBroad(_ ctx: CGContext, _ ink: HeroInk) {
        fillOval(ctx, CGRect(x: 13.5, y: 9, width: 21, height: 20), ink.cloak(0.7))
        strokeOval(ctx, CGRect(x: 13.5, y: 9, width: 21, height: 20), UIColor(rgb: 0x0B0908), width: 1.2)
        fillOval(ctx, CGRect(x: 17.5, y: 16.4, width: 13, height: 9.4), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 20.24, y: 19.8, width: 2, height: 1.6), ink.eyes())
        fillOval(ctx, CGRect(x: 25.55, y: 19.8, width: 2, height: 1.6), ink.eyes())
        strokeCurve(ctx, [P(15.27, 17.62), P(16.85, 13.8), P(19.5, 11.39), P(22.62, 10.27)], ink.cloak(1.7), width: 1)
    }

    // MARK: - heroHeadCowlBroad

    /// A hood with a cloth drawn across the mouth on a broad frame.
    static func heroHeadCowlBroad(_ ctx: CGContext, _ ink: HeroInk) {
        fillOval(ctx, CGRect(x: 13.5, y: 9, width: 21, height: 20), ink.cloak(0.7))
        strokeOval(ctx, CGRect(x: 13.5, y: 9, width: 21, height: 20), UIColor(rgb: 0x0B0908), width: 1.2)
        fillOval(ctx, CGRect(x: 17.5, y: 16.4, width: 13, height: 9.4), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 20.24, y: 19.8, width: 2, height: 1.6), ink.eyes())
        fillOval(ctx, CGRect(x: 25.55, y: 19.8, width: 2, height: 1.6), ink.eyes())
        strokeCurve(ctx, [P(15.27, 17.62), P(16.85, 13.8), P(19.5, 11.39), P(22.62, 10.27)], ink.cloak(1.7), width: 1)
        fillPolygon(ctx, [P(17.9, 22.17), P(24, 20.37), P(30.1, 22.17), P(29.5, 25.8), P(24, 27.4), P(18.5, 25.8)], ink.trim(0.55))
        strokePolygon(ctx, [P(17.9, 22.17), P(24, 20.37), P(30.1, 22.17), P(29.5, 25.8), P(24, 27.4), P(18.5, 25.8)], UIColor(rgb: 0x0B0908), width: 0.8)
        stroke(ctx, from: P(18.7, 23.97), to: P(29.3, 24.57), ink.trim(0.35), width: 0.7)
    }

    // MARK: - heroHeadBareBroad

    /// A bare head on a broad frame: skin, hair and open eyes.
    static func heroHeadBareBroad(_ ctx: CGContext, _ ink: HeroInk) {
        fillPolygon(ctx, [P(21.9, 24.5), P(26.1, 24.5), P(26.1, 30), P(21.9, 30)], ink.skin(0.66))
        fillOval(ctx, CGRect(x: 16.4, y: 9.5, width: 15.2, height: 15), ink.hair(0.8))
        strokeOval(ctx, CGRect(x: 16.4, y: 9.5, width: 15.2, height: 15), UIColor(rgb: 0x0B0908), width: 1)
        fillOval(ctx, CGRect(x: 18, y: 12, width: 12, height: 13.5), ink.skin())
        strokeOval(ctx, CGRect(x: 18, y: 12, width: 12, height: 13.5), UIColor(rgb: 0x0B0908), width: 1)
        fillSmooth(ctx, [P(17, 20.5), P(17.4, 14.5), P(20.5, 10.6), P(27.5, 10.6), P(30.6, 14.5), P(31, 20.5), P(29.4, 17.2), P(25.5, 15), P(21, 16.6), P(18.8, 18.2)], ink.hair())
        strokeSmooth(ctx, [P(17, 20.5), P(17.4, 14.5), P(20.5, 10.6), P(27.5, 10.6), P(30.6, 14.5), P(31, 20.5), P(29.4, 17.2), P(25.5, 15), P(21, 16.6), P(18.8, 18.2)], UIColor(rgb: 0x0B0908), width: 0.8)
        fillOval(ctx, CGRect(x: 20.5, y: 18.5, width: 2.2, height: 2.2), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 25.3, y: 18.5, width: 2.2, height: 2.2), UIColor(rgb: 0x120D0C))
        fillOval(ctx, CGRect(x: 20.85, y: 18.85, width: 1.5, height: 1.5), ink.eyes())
        fillOval(ctx, CGRect(x: 25.65, y: 18.85, width: 1.5, height: 1.5), ink.eyes())
        stroke(ctx, from: P(20.2, 17.6), to: P(22.7, 18.1), ink.hair(0.7), width: 0.8)
        stroke(ctx, from: P(25.3, 18.1), to: P(27.8, 17.6), ink.hair(0.7), width: 0.8)
        stroke(ctx, from: P(22.8, 23.4), to: P(25.2, 23.4), ink.skin(0.55), width: 0.7)
    }

    // MARK: - heroHeadHelmBroad

    /// An open iron helm on a broad frame, with a crest and lit eyes.
    static func heroHeadHelmBroad(_ ctx: CGContext, _ ink: HeroInk) {
        fillOval(ctx, CGRect(x: 16.2, y: 10, width: 15.6, height: 15), UIColor(rgb: 0x8A9098))
        strokeOval(ctx, CGRect(x: 16.2, y: 10, width: 15.6, height: 15), UIColor(rgb: 0x0B0908), width: 1.2)
        fillPolygon(ctx, [P(25, 10.4), P(31, 15), P(31.6, 20), P(25, 24)], ink.cloak(0.2).withAlphaComponent(0.18))
        fillPolygon(ctx, [P(19.2, 16.4), P(28.8, 16.4), P(27.8, 24.4), P(24, 26), P(20.2, 24.4)], UIColor(rgb: 0x120D0C))
        fillPolygon(ctx, [P(16.6, 19), P(17.4, 24.6), P(21, 26.4), P(21.4, 20.6)], UIColor(rgb: 0x6E747C))
        strokePolygon(ctx, [P(16.6, 19), P(17.4, 24.6), P(21, 26.4), P(21.4, 20.6)], UIColor(rgb: 0x0B0908), width: 0.9)
        fillPolygon(ctx, [P(31.4, 19), P(30.6, 24.6), P(27, 26.4), P(26.6, 20.6)], UIColor(rgb: 0x5C626A))
        strokePolygon(ctx, [P(31.4, 19), P(30.6, 24.6), P(27, 26.4), P(26.6, 20.6)], UIColor(rgb: 0x0B0908), width: 0.9)
        fillPolygon(ctx, [P(16.4, 15.4), P(31.6, 15.4), P(31.6, 17.3), P(16.4, 17.3)], UIColor(rgb: 0x6E747C))
        strokePolygon(ctx, [P(16.4, 15.4), P(31.6, 15.4), P(31.6, 17.3), P(16.4, 17.3)], UIColor(rgb: 0x0B0908), width: 0.6)
        fillPolygon(ctx, [P(23.1, 16), P(24.9, 16), P(24.9, 24.6), P(23.1, 24.6)], UIColor(rgb: 0x8A9098))
        strokePolygon(ctx, [P(23.1, 16), P(24.9, 16), P(24.9, 24.6), P(23.1, 24.6)], UIColor(rgb: 0x0B0908), width: 0.6)
        fillOval(ctx, CGRect(x: 19.6, y: 18.4, width: 2.2, height: 1.6), ink.eyes())
        fillOval(ctx, CGRect(x: 26.2, y: 18.4, width: 2.2, height: 1.6), ink.eyes())
        strokeCurve(ctx, [P(18.4, 14.6), P(19.4, 12), P(22.4, 10.8)], UIColor(rgb: 0xC9CFD6), width: 1)
        fillPolygon(ctx, [P(22.1, 10.4), P(24, 4.5), P(25.9, 10.4)], ink.trim())
        strokePolygon(ctx, [P(22.1, 10.4), P(24, 4.5), P(25.9, 10.4)], UIColor(rgb: 0x0B0908), width: 0.8)
    }

    // MARK: - Dispatch

    static func drawHeroLegs(_ build: BodyBuild, _ ctx: CGContext, _ ink: HeroInk) {
        switch build {
        case .lithe: heroLegsLithe(ctx, ink)
        case .standard: heroLegsStandard(ctx, ink)
        case .broad: heroLegsBroad(ctx, ink)
        }
    }

    static func drawHeroCloak(_ style: CloakStyle, _ build: BodyBuild, _ ctx: CGContext, _ ink: HeroInk) {
        switch (style, build) {
        case (.hooded, .lithe): heroCloakHoodedLithe(ctx, ink)
        case (.hooded, .standard): heroCloakHoodedStandard(ctx, ink)
        case (.hooded, .broad): heroCloakHoodedBroad(ctx, ink)
        case (.mantle, .lithe): heroCloakMantleLithe(ctx, ink)
        case (.mantle, .standard): heroCloakMantleStandard(ctx, ink)
        case (.mantle, .broad): heroCloakMantleBroad(ctx, ink)
        case (.longCoat, .lithe): heroCloakLongCoatLithe(ctx, ink)
        case (.longCoat, .standard): heroCloakLongCoatStandard(ctx, ink)
        case (.longCoat, .broad): heroCloakLongCoatBroad(ctx, ink)
        case (.shroud, .lithe): heroCloakShroudLithe(ctx, ink)
        case (.shroud, .standard): heroCloakShroudStandard(ctx, ink)
        case (.shroud, .broad): heroCloakShroudBroad(ctx, ink)
        case (.pilgrim, .lithe): heroCloakPilgrimLithe(ctx, ink)
        case (.pilgrim, .standard): heroCloakPilgrimStandard(ctx, ink)
        case (.pilgrim, .broad): heroCloakPilgrimBroad(ctx, ink)
        }
    }

    static func drawHeroHead(_ style: HeadStyle, _ build: BodyBuild, _ ctx: CGContext, _ ink: HeroInk) {
        switch (style, build) {
        case (.hood, .lithe): heroHeadHoodLithe(ctx, ink)
        case (.hood, .standard): heroHeadHoodStandard(ctx, ink)
        case (.hood, .broad): heroHeadHoodBroad(ctx, ink)
        case (.cowl, .lithe): heroHeadCowlLithe(ctx, ink)
        case (.cowl, .standard): heroHeadCowlStandard(ctx, ink)
        case (.cowl, .broad): heroHeadCowlBroad(ctx, ink)
        case (.bare, .lithe): heroHeadBareLithe(ctx, ink)
        case (.bare, .standard): heroHeadBareStandard(ctx, ink)
        case (.bare, .broad): heroHeadBareBroad(ctx, ink)
        case (.helm, .lithe): heroHeadHelmLithe(ctx, ink)
        case (.helm, .standard): heroHeadHelmStandard(ctx, ink)
        case (.helm, .broad): heroHeadHelmBroad(ctx, ink)
        }
    }
}
