import UIKit

// Generated by tools/art/props.py. Edit the Python and rerun it; do not edit
// this file by hand.

/// Set dressing that belongs to one realm and nowhere else: the props that
/// tell you where you are before anything attacks you.
///
/// Standing props stand on their base; decals lie flat and are anchored at
/// their centre. The drawing primitives these call live in
/// PlaceholderArt+Drawing.swift.
extension PlaceholderArt {

    // MARK: - reeds

    /// A stand of dead reeds, bent where something came through.
    static func reeds() -> Sprite {
        let image = render(CGSize(width: 34, height: 38)) { ctx in
            fillPolygon(ctx, [P(7.89, 35.86), P(7.08, 31.6), P(6.25, 27.58), P(5.39, 23.8), P(4.51, 20.28), P(3.62, 17), P(2.7, 13.98), P(2.5, 14.02), P(3.16, 17.11), P(3.8, 20.43), P(4.41, 24), P(5, 27.8), P(5.57, 31.85), P(6.11, 36.14)], UIColor(rgb: 0x404C24))
            fillPolygon(ctx, [P(11.9, 36.05), P(12.1, 30.21), P(12.32, 24.71), P(12.55, 19.54), P(12.79, 14.7), P(13.04, 10.19), P(13.3, 6.01), P(13.1, 5.99), P(12.57, 10.15), P(12.06, 14.64), P(11.55, 19.46), P(11.06, 24.62), P(10.57, 30.12), P(10.1, 35.95)], UIColor(rgb: 0x5A6A32))
            fillOval(ctx, CGRect(x: 11.9, y: 4, width: 2.6, height: 5), UIColor(rgb: 0x313A1B))
            strokeOval(ctx, CGRect(x: 11.9, y: 4, width: 2.6, height: 5), UIColor(rgb: 0x0E0C08), width: 0.4)
            fillPolygon(ctx, [P(15.9, 35.94), P(15.43, 30.89), P(14.94, 26.13), P(14.45, 21.66), P(13.94, 17.48), P(13.43, 13.59), P(12.9, 9.99), P(12.7, 10.01), P(12.96, 13.64), P(13.21, 17.55), P(13.45, 21.74), P(13.68, 26.23), P(13.9, 31), P(14.1, 36.06)], UIColor(rgb: 0x404C24))
            fillOval(ctx, CGRect(x: 11.5, y: 8, width: 2.6, height: 5), UIColor(rgb: 0x313A1B))
            strokeOval(ctx, CGRect(x: 11.5, y: 8, width: 2.6, height: 5), UIColor(rgb: 0x0E0C08), width: 0.4)
            fillPolygon(ctx, [P(19.9, 36.09), P(20.44, 29.67), P(21.01, 23.61), P(21.6, 17.92), P(22.21, 12.59), P(22.84, 7.62), P(23.5, 3.02), P(23.3, 2.98), P(22.38, 7.55), P(21.48, 12.48), P(20.6, 17.78), P(19.75, 23.46), P(18.92, 29.5), P(18.1, 35.91)], UIColor(rgb: 0x5A6A32))
            fillOval(ctx, CGRect(x: 22.1, y: 1, width: 2.6, height: 5), UIColor(rgb: 0x313A1B))
            strokeOval(ctx, CGRect(x: 22.1, y: 1, width: 2.6, height: 5), UIColor(rgb: 0x0E0C08), width: 0.4)
            fillPolygon(ctx, [P(23.9, 36), P(23.77, 31.33), P(23.63, 26.93), P(23.5, 22.8), P(23.37, 18.93), P(23.23, 15.33), P(23.1, 12), P(22.9, 12), P(22.77, 15.33), P(22.63, 18.93), P(22.5, 22.8), P(22.37, 26.93), P(22.23, 31.33), P(22.1, 36)], UIColor(rgb: 0x404C24))
            fillPolygon(ctx, [P(26.86, 36.25), P(27.75, 32.72), P(28.67, 29.4), P(29.62, 26.27), P(30.61, 23.34), P(31.63, 20.6), P(32.69, 18.04), P(32.51, 17.96), P(31.2, 20.4), P(29.93, 23.06), P(28.68, 25.93), P(27.47, 29), P(26.28, 32.28), P(25.14, 35.75)], UIColor(rgb: 0x5A6A32))
            fillOval(ctx, CGRect(x: 6, y: 33, width: 22, height: 5), UIColor(rgb: 0x282F16))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.05))
    }

    // MARK: - standingWater

    /// A pool of black water with something under it.
    static func standingWater() -> Sprite {
        let image = render(CGSize(width: 46, height: 30)) { ctx in
            fillSmooth(ctx, [P(4, 15), P(12, 5), P(26, 3), P(40, 9), P(42, 19), P(30, 26), P(13, 25)], UIColor(rgb: 0x24363A))
            strokeSmooth(ctx, [P(4, 15), P(12, 5), P(26, 3), P(40, 9), P(42, 19), P(30, 26), P(13, 25)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillSmooth(ctx, [P(9, 14), P(18, 8), P(30, 8), P(36, 14), P(28, 20), P(15, 20)], UIColor(rgb: 0x192528))
            strokeCurve(ctx, [P(12, 18), P(20, 15), P(30, 17)], UIColor(rgb: 0x3E5A5E), width: 1.2)
            strokeCurve(ctx, [P(18, 11), P(27, 10)], UIColor(rgb: 0x3E5A5E), width: 0.9)
            strokeCurve(ctx, [P(24, 21), P(33, 20)], UIColor(rgb: 0x3E5A5E), width: 0.7)
            fillPolygon(ctx, [P(30.69, 17.41), P(33.13, 12.08), P(32.87, 11.92), P(29.31, 16.59)], UIColor(rgb: 0xA89C80))
            strokePolygon(ctx, [P(30.69, 17.41), P(33.13, 12.08), P(32.87, 11.92), P(29.31, 16.59)], UIColor(rgb: 0x0E0C08), width: 0.4)
            fillPolygon(ctx, [P(33.49, 18.35), P(35.58, 14.56), P(35.42, 14.44), P(32.51, 17.65)], UIColor(rgb: 0xA89C80))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.5))
    }

    // MARK: - bogStump

    /// A rotted stump sunk to its knees in the mire.
    static func bogStump() -> Sprite {
        let image = render(CGSize(width: 30, height: 26)) { ctx in
            fillOval(ctx, CGRect(x: 3, y: 19, width: 24, height: 8), UIColor(rgb: 0x1C2B2E))
            fillSmooth(ctx, [P(7, 22), P(6, 11), P(11, 7), P(20, 8), P(23, 14), P(22, 23)], UIColor(rgb: 0x4A3A28))
            strokeSmooth(ctx, [P(7, 22), P(6, 11), P(11, 7), P(20, 8), P(23, 14), P(22, 23)], UIColor(rgb: 0x0E0C08), width: 1)
            fillSmooth(ctx, [P(8, 20), P(7.5, 12), P(11, 9), P(13, 21)], UIColor(rgb: 0x2E2418))
            fillOval(ctx, CGRect(x: 8, y: 5, width: 14, height: 6), UIColor(rgb: 0x6E6153))
            strokeOval(ctx, CGRect(x: 8, y: 5, width: 14, height: 6), UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 10, y: 6, width: 10, height: 4.2), UIColor(rgb: 0x2C2218))
            fillOval(ctx, CGRect(x: 11.5, y: 6.6, width: 7, height: 2.8), UIColor(rgb: 0x2E2418))
            fillPolygon(ctx, [P(20, 7), P(23, 2), P(22.5, 10)], UIColor(rgb: 0x6A5438))
            strokePolygon(ctx, [P(20, 7), P(23, 2), P(22.5, 10)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 4, y: 13.7, width: 5.2, height: 2.6), UIColor(rgb: 0x939E79))
            strokeOval(ctx, CGRect(x: 4, y: 13.7, width: 5.2, height: 2.6), UIColor(rgb: 0x0E0C08), width: 0.4)
            fillOval(ctx, CGRect(x: 4.5, y: 13.9, width: 2.6, height: 1.2), UIColor(rgb: 0xBDC3AD))
            fillOval(ctx, CGRect(x: 5.3, y: 16.7, width: 4.2, height: 2.6), UIColor(rgb: 0x939E79))
            strokeOval(ctx, CGRect(x: 5.3, y: 16.7, width: 4.2, height: 2.6), UIColor(rgb: 0x0E0C08), width: 0.4)
            fillOval(ctx, CGRect(x: 5.8, y: 16.9, width: 2.1, height: 1.2), UIColor(rgb: 0xBDC3AD))
            fillOval(ctx, CGRect(x: 4.4, y: 10.7, width: 3.6, height: 2.6), UIColor(rgb: 0x939E79))
            strokeOval(ctx, CGRect(x: 4.4, y: 10.7, width: 3.6, height: 2.6), UIColor(rgb: 0x0E0C08), width: 0.4)
            fillOval(ctx, CGRect(x: 4.9, y: 10.9, width: 1.8, height: 1.2), UIColor(rgb: 0xBDC3AD))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.08))
    }

    // MARK: - pineTree

    /// A black pine, still alive, and not glad about it.
    static func pineTree() -> Sprite {
        let image = render(CGSize(width: 40, height: 72)) { ctx in
            fillOval(ctx, CGRect(x: 12, y: 66, width: 16, height: 6), UIColor(rgb: 0x1D1710))
            fillPolygon(ctx, [P(23.25, 68.9), P(22.7, 60.23), P(22.26, 52.18), P(21.93, 44.75), P(21.71, 37.93), P(21.6, 31.71), P(21.6, 26.08), P(18.4, 25.92), P(17.85, 31.57), P(17.41, 37.85), P(17.07, 44.75), P(16.86, 52.26), P(16.75, 60.38), P(16.75, 69.1)], UIColor(rgb: 0x4A3A28))
            strokePolygon(ctx, [P(23.25, 68.9), P(22.7, 60.23), P(22.26, 52.18), P(21.93, 44.75), P(21.71, 37.93), P(21.6, 31.71), P(21.6, 26.08), P(18.4, 25.92), P(17.85, 31.57), P(17.41, 37.85), P(17.07, 44.75), P(16.86, 52.26), P(16.75, 60.38), P(16.75, 69.1)], UIColor(rgb: 0x0E0C08), width: 0.8)
            fillPolygon(ctx, [P(19.6, 66.96), P(18.2, 39.97), P(16.8, 40.03), P(17.4, 67.04)], UIColor(rgb: 0x2E2418))
            fillSmooth(ctx, [P(3, 46), P(13.2, 37), P(20, 32.5), P(26.8, 37), P(37, 46), P(28.5, 50.5), P(20, 52.3), P(11.5, 50.5)], UIColor(rgb: 0x22331E))
            strokeSmooth(ctx, [P(3, 46), P(13.2, 37), P(20, 32.5), P(26.8, 37), P(37, 46), P(28.5, 50.5), P(20, 52.3), P(11.5, 50.5)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillSmooth(ctx, [P(6.4, 46), P(14.9, 39.7), P(19, 49.6)], UIColor(rgb: 0x172315))
            fillPolygon(ctx, [P(9.22, 42.91), P(4.58, 50.87), P(4.82, 51.03), P(10.38, 43.69)], UIColor(rgb: 0x495746))
            fillPolygon(ctx, [P(14.24, 43.08), P(12.21, 50.9), P(12.49, 51), P(15.56, 43.52)], UIColor(rgb: 0x495746))
            fillPolygon(ctx, [P(19.3, 43.3), P(19.85, 50.95), P(20.15, 50.95), P(20.7, 43.3)], UIColor(rgb: 0x495746))
            fillPolygon(ctx, [P(24.44, 43.52), P(27.51, 51), P(27.79, 50.9), P(25.76, 43.08)], UIColor(rgb: 0x495746))
            fillPolygon(ctx, [P(29.62, 43.69), P(35.18, 51.03), P(35.42, 50.87), P(30.78, 42.91)], UIColor(rgb: 0x495746))
            fillSmooth(ctx, [P(7, 32), P(14.8, 24), P(20, 20), P(25.2, 24), P(33, 32), P(26.5, 36), P(20, 37.6), P(13.5, 36)], UIColor(rgb: 0x2E4428))
            strokeSmooth(ctx, [P(7, 32), P(14.8, 24), P(20, 20), P(25.2, 24), P(33, 32), P(26.5, 36), P(20, 37.6), P(13.5, 36)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillSmooth(ctx, [P(9.6, 32), P(16.1, 26.4), P(19, 35.2)], UIColor(rgb: 0x202F1C))
            fillPolygon(ctx, [P(11.59, 29.25), P(8.17, 36.33), P(8.43, 36.47), P(12.81, 29.95)], UIColor(rgb: 0x53654E))
            fillPolygon(ctx, [P(15.43, 29.41), P(14.01, 36.36), P(14.29, 36.44), P(16.77, 29.79)], UIColor(rgb: 0x53654E))
            fillPolygon(ctx, [P(19.3, 29.6), P(19.85, 36.4), P(20.15, 36.4), P(20.7, 29.6)], UIColor(rgb: 0x53654E))
            fillPolygon(ctx, [P(23.23, 29.79), P(25.71, 36.44), P(25.99, 36.36), P(24.57, 29.41)], UIColor(rgb: 0x53654E))
            fillPolygon(ctx, [P(27.19, 29.95), P(31.57, 36.47), P(31.83, 36.33), P(28.41, 29.25)], UIColor(rgb: 0x53654E))
            fillSmooth(ctx, [P(11, 20), P(16.4, 13), P(20, 9.5), P(23.6, 13), P(29, 20), P(24.5, 23.5), P(20, 24.9), P(15.5, 23.5)], UIColor(rgb: 0x22331E))
            strokeSmooth(ctx, [P(11, 20), P(16.4, 13), P(20, 9.5), P(23.6, 13), P(29, 20), P(24.5, 23.5), P(20, 24.9), P(15.5, 23.5)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillSmooth(ctx, [P(12.8, 20), P(17.3, 15.1), P(19, 22.8)], UIColor(rgb: 0x172315))
            fillPolygon(ctx, [P(13.96, 17.61), P(11.76, 23.79), P(12.04, 23.91), P(15.24, 18.19)], UIColor(rgb: 0x495746))
            fillPolygon(ctx, [P(16.62, 17.75), P(15.8, 23.82), P(16.1, 23.88), P(17.98, 18.05)], UIColor(rgb: 0x495746))
            fillPolygon(ctx, [P(19.3, 17.9), P(19.85, 23.85), P(20.15, 23.85), P(20.7, 17.9)], UIColor(rgb: 0x495746))
            fillPolygon(ctx, [P(22.02, 18.05), P(23.9, 23.88), P(24.2, 23.82), P(23.38, 17.75)], UIColor(rgb: 0x495746))
            fillPolygon(ctx, [P(24.76, 18.19), P(27.96, 23.91), P(28.24, 23.79), P(26.04, 17.61)], UIColor(rgb: 0x495746))
            fillPolygon(ctx, [P(20, 20), P(22, 10), P(18.5, 12)], UIColor(rgb: 0x243620))
            strokePolygon(ctx, [P(20, 20), P(22, 10), P(18.5, 12)], UIColor(rgb: 0x0E0C08), width: 0.6)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.03))
    }

    // MARK: - forestStump

    /// A stump cut clean, a long time ago.
    static func forestStump() -> Sprite {
        let image = render(CGSize(width: 28, height: 22)) { ctx in
            fillOval(ctx, CGRect(x: 3, y: 16, width: 22, height: 7), UIColor(rgb: 0x1D1710))
            fillSmooth(ctx, [P(6, 19), P(6, 9), P(21, 9), P(21, 19)], UIColor(rgb: 0x4A3A28))
            strokeSmooth(ctx, [P(6, 19), P(6, 9), P(21, 9), P(21, 19)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillSmooth(ctx, [P(6.5, 18), P(6.5, 10), P(11, 10), P(11, 18)], UIColor(rgb: 0x2E2418))
            fillOval(ctx, CGRect(x: 5, y: 5, width: 18, height: 8), UIColor(rgb: 0x776B5D))
            strokeOval(ctx, CGRect(x: 5, y: 5, width: 18, height: 8), UIColor(rgb: 0x0E0C08), width: 0.8)
            fillOval(ctx, CGRect(x: 7.25, y: 6, width: 13.5, height: 6), UIColor(rgb: 0x423424))
            fillOval(ctx, CGRect(x: 9.5, y: 7, width: 9, height: 4), UIColor(rgb: 0x3F3122))
            fillOval(ctx, CGRect(x: 11.48, y: 7.88, width: 5.04, height: 2.24), UIColor(rgb: 0x3C2F20))
            strokeCurve(ctx, [P(9, 7), P(14, 8.5), P(19, 7)], UIColor(rgb: 0x2E2418), width: 0.6)
            fillPolygon(ctx, [P(3.65, 16.15), P(1.15, 19.65), P(1.85, 20.35), P(5.35, 17.85)], UIColor(rgb: 0x2E2418))
            fillPolygon(ctx, [P(21.15, 16.85), P(24.65, 19.35), P(25.35, 18.65), P(22.85, 15.15)], UIColor(rgb: 0x2E2418))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.09))
    }

    // MARK: - mushrooms

    /// A cluster of pale caps, faintly lit from underneath.
    static func mushrooms() -> Sprite {
        let image = render(CGSize(width: 30, height: 24)) { ctx in
            radialGradient(ctx, center: P(15, 14), radius: 12, inner: UIColor(rgb: 0x9FE0B0, alpha: 0.35), outer: UIColor(rgb: 0x9FE0B0, alpha: 0))
            fillPolygon(ctx, [P(10.14, 20.82), P(8.83, 14.57), P(7.17, 14.83), P(7.86, 21.18)], UIColor(rgb: 0xE4DCC4))
            strokePolygon(ctx, [P(10.14, 20.82), P(8.83, 14.57), P(7.17, 14.83), P(7.86, 21.18)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillSmooth(ctx, [P(3.8, 15.12), P(5.9, 11.76), P(10.1, 11.76), P(12.2, 15.12), P(8, 16.38)], UIColor(rgb: 0xC8D8BC))
            strokeSmooth(ctx, [P(3.8, 15.12), P(5.9, 11.76), P(10.1, 11.76), P(12.2, 15.12), P(8, 16.38)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillSmooth(ctx, [P(4.64, 14.7), P(6.74, 12.6), P(8.42, 14.7)], UIColor(rgb: 0xDEE7D6))
            fillOval(ctx, CGRect(x: 8.59, y: 12.98, width: 1.34, height: 1.34), UIColor(rgb: 0x8AA87A))
            fillPolygon(ctx, [P(17.54, 20.09), P(17.62, 11.67), P(15.38, 11.53), P(14.46, 19.91)], UIColor(rgb: 0xE4DCC4))
            strokePolygon(ctx, [P(17.54, 20.09), P(17.62, 11.67), P(15.38, 11.53), P(14.46, 19.91)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillSmooth(ctx, [P(10.9, 12.16), P(13.7, 7.68), P(19.3, 7.68), P(22.1, 12.16), P(16.5, 13.84)], UIColor(rgb: 0xC8D8BC))
            strokeSmooth(ctx, [P(10.9, 12.16), P(13.7, 7.68), P(19.3, 7.68), P(22.1, 12.16), P(16.5, 13.84)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillSmooth(ctx, [P(12.02, 11.6), P(14.82, 8.8), P(17.06, 11.6)], UIColor(rgb: 0xDEE7D6))
            fillOval(ctx, CGRect(x: 17.28, y: 9.3, width: 1.79, height: 1.79), UIColor(rgb: 0x8AA87A))
            fillPolygon(ctx, [P(22.91, 21.21), P(23.86, 16.06), P(22.54, 15.74), P(21.09, 20.79)], UIColor(rgb: 0xE4DCC4))
            strokePolygon(ctx, [P(22.91, 21.21), P(23.86, 16.06), P(22.54, 15.74), P(21.09, 20.79)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillSmooth(ctx, [P(19.8, 16.24), P(21.5, 13.52), P(24.9, 13.52), P(26.6, 16.24), P(23.2, 17.26)], UIColor(rgb: 0xC8D8BC))
            strokeSmooth(ctx, [P(19.8, 16.24), P(21.5, 13.52), P(24.9, 13.52), P(26.6, 16.24), P(23.2, 17.26)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillSmooth(ctx, [P(20.48, 15.9), P(22.18, 14.2), P(23.54, 15.9)], UIColor(rgb: 0xDEE7D6))
            fillOval(ctx, CGRect(x: 23.68, y: 14.51, width: 1.09, height: 1.09), UIColor(rgb: 0x8AA87A))
            fillPolygon(ctx, [P(13.71, 21.93), P(13.12, 18.05), P(12.08, 18.15), P(12.29, 22.07)], UIColor(rgb: 0xE4DCC4))
            strokePolygon(ctx, [P(13.71, 21.93), P(13.12, 18.05), P(12.08, 18.15), P(12.29, 22.07)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillSmooth(ctx, [P(10, 18.36), P(11.3, 16.28), P(13.9, 16.28), P(15.2, 18.36), P(12.6, 19.14)], UIColor(rgb: 0xC8D8BC))
            strokeSmooth(ctx, [P(10, 18.36), P(11.3, 16.28), P(13.9, 16.28), P(15.2, 18.36), P(12.6, 19.14)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillSmooth(ctx, [P(10.52, 18.1), P(11.82, 16.8), P(12.86, 18.1)], UIColor(rgb: 0xDEE7D6))
            fillOval(ctx, CGRect(x: 12.96, y: 17.03, width: 0.83, height: 0.83), UIColor(rgb: 0x8AA87A))
            fillOval(ctx, CGRect(x: 5, y: 20, width: 22, height: 5), UIColor(rgb: 0x172214))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.08))
    }

    // MARK: - iceSpire

    /// A spire of river ice, blue at the root.
    static func iceSpire() -> Sprite {
        let image = render(CGSize(width: 34, height: 56)) { ctx in
            radialGradient(ctx, center: P(17, 34), radius: 20, inner: UIColor(rgb: 0xA8D4E4, alpha: 0.25), outer: UIColor(rgb: 0xA8D4E4, alpha: 0))
            fillOval(ctx, CGRect(x: 5, y: 49, width: 24, height: 8), UIColor(rgb: 0x3A5C6D))
            fillPolygon(ctx, [P(11, 53), P(14, 20), P(18, 6), P(21, 24), P(23, 53)], UIColor(rgb: 0xA8D4E4))
            strokePolygon(ctx, [P(11, 53), P(14, 20), P(18, 6), P(21, 24), P(23, 53)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillPolygon(ctx, [P(14, 20), P(18, 6), P(19.5, 24), P(16, 48)], UIColor(rgb: 0xDCF0F8))
            fillPolygon(ctx, [P(11, 53), P(14, 20), P(15.5, 34), P(14, 53)], UIColor(rgb: 0x5A8EA8))
            stroke(ctx, from: P(16, 14), to: P(17, 42), UIColor(rgb: 0xEDF7FB), width: 0.8)
            fillPolygon(ctx, [P(6, 53), P(8, 36), P(11, 53)], UIColor(rgb: 0xA8D4E4))
            strokePolygon(ctx, [P(6, 53), P(8, 36), P(11, 53)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(23, 53), P(26, 40), P(28, 53)], UIColor(rgb: 0xA8D4E4))
            strokePolygon(ctx, [P(23, 53), P(26, 40), P(28, 53)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(8, 36), P(9.5, 46), P(8.5, 52)], UIColor(rgb: 0xDCF0F8))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.04))
    }

    // MARK: - frozenCorpse

    /// Someone who sat down out of the wind and stayed.
    static func frozenCorpse() -> Sprite {
        let image = render(CGSize(width: 40, height: 28)) { ctx in
            fillSmooth(ctx, [P(4, 17), P(12, 10), P(26, 9), P(36, 15), P(33, 23), P(15, 24)], UIColor(rgb: 0x497489))
            strokeSmooth(ctx, [P(4, 17), P(12, 10), P(26, 9), P(36, 15), P(33, 23), P(15, 24)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillSmooth(ctx, [P(9, 17), P(18, 13), P(29, 14), P(31, 19), P(18, 21)], UIColor(rgb: 0x6D9BB2))
            fillSmooth(ctx, [P(9, 16), P(11, 11), P(16, 10), P(19, 13), P(18, 17)], UIColor(rgb: 0x4E4E52))
            strokeSmooth(ctx, [P(9, 16), P(11, 11), P(16, 10), P(19, 13), P(18, 17)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(10, 14), P(18, 13), P(18.4, 15.2), P(10.2, 16.2)], UIColor(rgb: 0x16110E))
            strokeCurve(ctx, [P(11, 11.4), P(15, 10.4)], UIColor(rgb: 0x7A7A7E), width: 0.7)
            fillPolygon(ctx, [P(22.82, 19.49), P(24.75, 18.31), P(26.55, 16.99), P(28.18, 15.55), P(29.62, 13.99), P(30.88, 12.33), P(31.91, 10.61), P(30.09, 9.39), P(28.96, 10.89), P(27.71, 12.23), P(26.32, 13.45), P(24.78, 14.57), P(23.09, 15.58), P(21.18, 16.51)], UIColor(rgb: 0x4E4E52))
            strokePolygon(ctx, [P(22.82, 19.49), P(24.75, 18.31), P(26.55, 16.99), P(28.18, 15.55), P(29.62, 13.99), P(30.88, 12.33), P(31.91, 10.61), P(30.09, 9.39), P(28.96, 10.89), P(27.71, 12.23), P(26.32, 13.45), P(24.78, 14.57), P(23.09, 15.58), P(21.18, 16.51)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillOval(ctx, CGRect(x: 29, y: 7.5, width: 4.6, height: 4.4), UIColor(rgb: 0xA89C80))
            strokeOval(ctx, CGRect(x: 29, y: 7.5, width: 4.6, height: 4.4), UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(29.94, 7.68), P(30.07, 3.61), P(29.93, 3.59), P(28.86, 7.52)], UIColor(rgb: 0xD8CDB0))
            fillPolygon(ctx, [P(31.74, 7.28), P(31.87, 3.21), P(31.73, 3.19), P(30.66, 7.12)], UIColor(rgb: 0xD8CDB0))
            fillPolygon(ctx, [P(33.14, 8.48), P(33.27, 4.41), P(33.13, 4.39), P(32.06, 8.32)], UIColor(rgb: 0xD8CDB0))
            strokeCurve(ctx, [P(8, 20), P(18, 22), P(31, 20)], UIColor(rgb: 0xE8F5FA), width: 1)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.5))
    }

    // MARK: - gibbet

    /// A gibbet, still occupied.
    static func gibbet() -> Sprite {
        let image = render(CGSize(width: 36, height: 64)) { ctx in
            fillOval(ctx, CGRect(x: 6, y: 58, width: 16, height: 6), UIColor(rgb: 0x1D1710))
            fillPolygon(ctx, [P(14.1, 60.93), P(13.69, 51.36), P(13.34, 41.95), P(13.05, 32.72), P(12.81, 23.65), P(12.63, 14.74), P(12.5, 6), P(9.5, 6), P(9.43, 14.76), P(9.41, 23.69), P(9.45, 32.78), P(9.54, 42.05), P(9.7, 51.48), P(9.9, 61.07)], UIColor(rgb: 0x4A3A28))
            strokePolygon(ctx, [P(14.1, 60.93), P(13.69, 51.36), P(13.34, 41.95), P(13.05, 32.72), P(12.81, 23.65), P(12.63, 14.74), P(12.5, 6), P(9.5, 6), P(9.43, 14.76), P(9.41, 23.69), P(9.45, 32.78), P(9.54, 42.05), P(9.7, 51.48), P(9.9, 61.07)], UIColor(rgb: 0x0E0C08), width: 0.8)
            fillPolygon(ctx, [P(11.31, 8.57), P(14.25, 7.95), P(17.17, 7.49), P(20.08, 7.2), P(23, 7.07), P(25.93, 7.1), P(28.89, 7.3), P(29.11, 4.7), P(26.07, 4.4), P(23, 4.27), P(19.92, 4.3), P(16.83, 4.51), P(13.75, 4.89), P(10.69, 5.43)], UIColor(rgb: 0x4A3A28))
            strokePolygon(ctx, [P(11.31, 8.57), P(14.25, 7.95), P(17.17, 7.49), P(20.08, 7.2), P(23, 7.07), P(25.93, 7.1), P(28.89, 7.3), P(29.11, 4.7), P(26.07, 4.4), P(23, 4.27), P(19.92, 4.3), P(16.83, 4.51), P(13.75, 4.89), P(10.69, 5.43)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(12, 10), P(12, 14), P(18, 8), P(18, 5)], UIColor(rgb: 0x6A5438))
            strokePolygon(ctx, [P(12, 10), P(12, 14), P(18, 8), P(18, 5)], UIColor(rgb: 0x0E0C08), width: 0.5)
            stroke(ctx, from: P(28, 7), to: P(28, 16), UIColor(rgb: 0x5E5A54), width: 0.9)
            fillSmooth(ctx, [P(22, 16), P(34, 16), P(33, 34), P(23, 34)], UIColor(rgb: 0x4B4843))
            strokeSmooth(ctx, [P(22, 16), P(34, 16), P(33, 34), P(23, 34)], UIColor(rgb: 0x0E0C08), width: 0.8)
            stroke(ctx, from: P(24.5, 17), to: P(24.5, 33), UIColor(rgb: 0x8E8A80), width: 0.8)
            stroke(ctx, from: P(28, 17), to: P(28, 33), UIColor(rgb: 0x8E8A80), width: 0.8)
            stroke(ctx, from: P(31.5, 17), to: P(31.5, 33), UIColor(rgb: 0x8E8A80), width: 0.8)
            stroke(ctx, from: P(23, 20), to: P(33.2, 20), UIColor(rgb: 0x8E8A80), width: 0.7)
            stroke(ctx, from: P(23, 26), to: P(33.2, 26), UIColor(rgb: 0x8E8A80), width: 0.7)
            stroke(ctx, from: P(23, 31), to: P(33.2, 31), UIColor(rgb: 0x8E8A80), width: 0.7)
            fillOval(ctx, CGRect(x: 25.5, y: 19, width: 7, height: 6.5), UIColor(rgb: 0xA89C80))
            strokeOval(ctx, CGRect(x: 25.5, y: 19, width: 7, height: 6.5), UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 27.5, y: 21, width: 2, height: 2.2), UIColor(rgb: 0x16110E))
            fillSmooth(ctx, [P(25, 25), P(32, 25), P(31, 32), P(26, 32)], UIColor(rgb: 0x3A3230))
            strokeCurve(ctx, [P(25.5, 27), P(31, 27.8)], UIColor(rgb: 0x6E6450), width: 0.7)
            strokeCurve(ctx, [P(25.5, 30), P(31, 30.8)], UIColor(rgb: 0x6E6450), width: 0.7)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.03))
    }

    // MARK: - warBanner

    /// A banner nobody came back for.
    static func warBanner() -> Sprite {
        let image = render(CGSize(width: 30, height: 58)) { ctx in
            fillOval(ctx, CGRect(x: 9, y: 52, width: 12, height: 5), UIColor(rgb: 0x46433E))
            fillPolygon(ctx, [P(15.3, 55), P(15.22, 46.08), P(15.09, 37.32), P(14.9, 28.73), P(14.66, 20.3), P(14.35, 12.05), P(14, 3.96), P(12, 4.04), P(12.26, 12.12), P(12.46, 20.36), P(12.6, 28.77), P(12.69, 37.35), P(12.72, 46.09), P(12.7, 55)], UIColor(rgb: 0x4A3A28))
            strokePolygon(ctx, [P(15.3, 55), P(15.22, 46.08), P(15.09, 37.32), P(14.9, 28.73), P(14.66, 20.3), P(14.35, 12.05), P(14, 3.96), P(12, 4.04), P(12.26, 12.12), P(12.46, 20.36), P(12.6, 28.77), P(12.69, 37.35), P(12.72, 46.09), P(12.7, 55)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(13, 4), P(11, -1), P(16, 0)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(13, 4), P(11, -1), P(16, 0)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillSmooth(ctx, [P(14, 6), P(26, 8), P(25, 30), P(14, 28)], UIColor(rgb: 0x6E2320))
            strokeSmooth(ctx, [P(14, 6), P(26, 8), P(25, 30), P(14, 28)], UIColor(rgb: 0x0E0C08), width: 0.8)
            fillSmooth(ctx, [P(14, 8), P(18, 9), P(17.5, 28), P(14, 27)], UIColor(rgb: 0x4D1816))
            strokeCurve(ctx, [P(20, 9), P(21, 18), P(20.5, 28)], UIColor(rgb: 0x8D5351), width: 1.1)
            fillPolygon(ctx, [P(14.21, 28.15), P(16.1, 35.02), P(16.5, 34.98), P(16.79, 27.85)], UIColor(rgb: 0x6E2320))
            fillPolygon(ctx, [P(17.71, 28.15), P(19.6, 35.02), P(20, 34.98), P(20.29, 27.85)], UIColor(rgb: 0x6E2320))
            fillPolygon(ctx, [P(21.21, 28.15), P(23.1, 35.02), P(23.5, 34.98), P(23.79, 27.85)], UIColor(rgb: 0x6E2320))
            fillPolygon(ctx, [P(18, 14), P(22, 18), P(18, 22), P(14.8, 18)], UIColor(rgb: 0xC9A24A))
            strokePolygon(ctx, [P(18, 14), P(22, 18), P(18, 22), P(14.8, 18)], UIColor(rgb: 0x0E0C08), width: 0.5)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.03))
    }

    // MARK: - lavaVent

    /// A split in the rock with the Depths showing through.
    static func lavaVent() -> Sprite {
        let image = render(CGSize(width: 42, height: 30)) { ctx in
            fillSmooth(ctx, [P(4, 15), P(13, 6), P(28, 5), P(38, 12), P(35, 23), P(18, 25)], UIColor(rgb: 0x1E1A24))
            strokeSmooth(ctx, [P(4, 15), P(13, 6), P(28, 5), P(38, 12), P(35, 23), P(18, 25)], UIColor(rgb: 0x0E0C08), width: 0.9)
            radialGradient(ctx, center: P(21, 15), radius: 18, inner: UIColor(rgb: 0xE2601A, alpha: 0.75), outer: UIColor(rgb: 0xE2601A, alpha: 0))
            fillSmooth(ctx, [P(10, 15), P(17, 10), P(28, 10), P(33, 15), P(26, 20), P(15, 20)], UIColor(rgb: 0xE2601A))
            fillSmooth(ctx, [P(15, 15), P(20, 12), P(27, 13), P(28, 16), P(22, 18), P(17, 17)], UIColor(rgb: 0xFFC24A))
            strokeCurve(ctx, [P(10, 15), P(5, 11), P(2, 12)], UIColor(rgb: 0xE2601A), width: 1.3)
            strokeCurve(ctx, [P(10, 15), P(5, 11)], UIColor(rgb: 0xFFC24A), width: 0.6)
            strokeCurve(ctx, [P(33, 15), P(38, 18), P(41, 17)], UIColor(rgb: 0xE2601A), width: 1.3)
            strokeCurve(ctx, [P(33, 15), P(38, 18)], UIColor(rgb: 0xFFC24A), width: 0.6)
            strokeCurve(ctx, [P(22, 20), P(24, 25), P(22, 28)], UIColor(rgb: 0xE2601A), width: 1.3)
            strokeCurve(ctx, [P(22, 20), P(24, 25)], UIColor(rgb: 0xFFC24A), width: 0.6)
            strokeCurve(ctx, [P(18, 10), P(16, 5), P(18, 2)], UIColor(rgb: 0xE2601A), width: 1.3)
            strokeCurve(ctx, [P(18, 10), P(16, 5)], UIColor(rgb: 0xFFC24A), width: 0.6)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.5))
    }

    // MARK: - obsidianShard

    /// A blade of cooled glass, still warm to stand near.
    static func obsidianShard() -> Sprite {
        let image = render(CGSize(width: 32, height: 46)) { ctx in
            fillOval(ctx, CGRect(x: 6, y: 40, width: 20, height: 7), UIColor(rgb: 0x151219))
            fillPolygon(ctx, [P(10, 43), P(14, 18), P(19, 4), P(21, 22), P(23, 43)], UIColor(rgb: 0x1E1A24))
            strokePolygon(ctx, [P(10, 43), P(14, 18), P(19, 4), P(21, 22), P(23, 43)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillPolygon(ctx, [P(14, 18), P(19, 4), P(20, 22), P(16, 40)], UIColor(rgb: 0x4F4C54))
            stroke(ctx, from: P(17, 10), to: P(18, 34), UIColor(rgb: 0x8E8C91), width: 0.8)
            radialGradient(ctx, center: P(17, 38), radius: 11, inner: UIColor(rgb: 0xE2601A, alpha: 0.4), outer: UIColor(rgb: 0xE2601A, alpha: 0))
            strokeCurve(ctx, [P(12, 36), P(16, 33), P(21, 37)], UIColor(rgb: 0xE2601A), width: 1.1)
            fillPolygon(ctx, [P(5, 43), P(8, 29), P(11, 43)], UIColor(rgb: 0x1E1A24))
            strokePolygon(ctx, [P(5, 43), P(8, 29), P(11, 43)], UIColor(rgb: 0x0E0C08), width: 0.7)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.04))
    }

    // MARK: - voidRift

    /// A tear in the ground with nothing behind it.
    static func voidRift() -> Sprite {
        let image = render(CGSize(width: 44, height: 34)) { ctx in
            radialGradient(ctx, center: P(22, 17), radius: 22, inner: UIColor(rgb: 0x5A3F8C, alpha: 0.55), outer: UIColor(rgb: 0x5A3F8C, alpha: 0))
            fillSmooth(ctx, [P(6, 17), P(14, 8), P(26, 6), P(38, 14), P(33, 26), P(18, 28)], UIColor(rgb: 0x241938))
            strokeSmooth(ctx, [P(6, 17), P(14, 8), P(26, 6), P(38, 14), P(33, 26), P(18, 28)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillSmooth(ctx, [P(11, 17), P(18, 11), P(28, 11), P(33, 17), P(26, 23), P(16, 23)], UIColor(rgb: 0x0A0710))
            fillPolygon(ctx, [P(13.44, 18.64), P(16.32, 17.63), P(19.2, 17.01), P(22.2, 16.75), P(25.31, 16.87), P(28.55, 17.37), P(31.9, 18.28), P(32.1, 17.72), P(28.84, 16.35), P(25.57, 15.36), P(22.3, 14.75), P(19.02, 14.55), P(15.74, 14.76), P(12.56, 15.36)], UIColor(rgb: 0xC79BFF))
            fillPolygon(ctx, [P(17.11, 22.89), P(25.02, 21.15), P(24.98, 20.85), P(16.89, 21.11)], UIColor(rgb: 0xC79BFF))
            strokeCurve(ctx, [P(11, 17), P(7, 15.5), P(3, 14)], UIColor(rgb: 0x5A3F8C), width: 1.2)
            strokeCurve(ctx, [P(33, 17), P(37, 19), P(41, 21)], UIColor(rgb: 0x5A3F8C), width: 1.2)
            strokeCurve(ctx, [P(22, 11), P(21, 7), P(20, 3)], UIColor(rgb: 0x5A3F8C), width: 1.2)
            strokeCurve(ctx, [P(24, 24), P(25.5, 28), P(27, 32)], UIColor(rgb: 0x5A3F8C), width: 1.2)
            fillOval(ctx, CGRect(x: 20.4, y: 15.4, width: 3.2, height: 3.2), UIColor(rgb: 0xFFFFFF))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.5))
    }

    // MARK: - floatingStone

    /// A slab that forgot to fall, turning where it stopped.
    static func floatingStone() -> Sprite {
        let image = render(CGSize(width: 36, height: 44)) { ctx in
            radialGradient(ctx, center: P(18, 26), radius: 14, inner: UIColor(rgb: 0x5A3F8C, alpha: 0.3), outer: UIColor(rgb: 0x5A3F8C, alpha: 0))
            fillPolygon(ctx, [P(8, 20), P(20, 14), P(30, 19), P(26, 27), P(13, 28)], UIColor(rgb: 0x6A6660))
            strokePolygon(ctx, [P(8, 20), P(20, 14), P(30, 19), P(26, 27), P(13, 28)], UIColor(rgb: 0x0E0C08), width: 1)
            fillPolygon(ctx, [P(8, 20), P(20, 14), P(26, 18), P(13, 23)], UIColor(rgb: 0x8A8680))
            fillPolygon(ctx, [P(13, 23), P(26, 18), P(26, 27), P(13, 28)], UIColor(rgb: 0x46433E))
            stroke(ctx, from: P(16, 23), to: P(17, 27), UIColor(rgb: 0x353330), width: 0.6)
            stroke(ctx, from: P(21, 23), to: P(22, 27), UIColor(rgb: 0x353330), width: 0.6)
            fillPolygon(ctx, [P(4, 33), P(10, 30), P(12, 35), P(6, 37)], UIColor(rgb: 0x6A6660))
            strokePolygon(ctx, [P(4, 33), P(10, 30), P(12, 35), P(6, 37)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(27, 33), P(33, 31), P(33, 36), P(28, 37)], UIColor(rgb: 0x6A6660))
            strokePolygon(ctx, [P(27, 33), P(33, 31), P(33, 36), P(28, 37)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(17, 8), P(23, 6), P(24, 11), P(18, 12)], UIColor(rgb: 0x6A6660))
            strokePolygon(ctx, [P(17, 8), P(23, 6), P(24, 11), P(18, 12)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 14.2, y: 30.2, width: 1.6, height: 1.6), UIColor(rgb: 0xC79BFF))
            fillOval(ctx, CGRect(x: 19.2, y: 32.2, width: 1.6, height: 1.6), UIColor(rgb: 0xC79BFF))
            fillOval(ctx, CGRect(x: 23.2, y: 29.2, width: 1.6, height: 1.6), UIColor(rgb: 0xC79BFF))
            fillOval(ctx, CGRect(x: 17.2, y: 35.2, width: 1.6, height: 1.6), UIColor(rgb: 0xC79BFF))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.05))
    }

    // MARK: - brokenStatue

    /// A knight with the head struck off, still at attention.
    static func brokenStatue() -> Sprite {
        let image = render(CGSize(width: 34, height: 58)) { ctx in
            fillPolygon(ctx, [P(5, 55), P(29, 55), P(27, 47), P(7, 47)], UIColor(rgb: 0x46433E))
            strokePolygon(ctx, [P(5, 55), P(29, 55), P(27, 47), P(7, 47)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillPolygon(ctx, [P(7, 47), P(27, 47), P(26, 44), P(8, 44)], UIColor(rgb: 0x6A6660))
            strokePolygon(ctx, [P(7, 47), P(27, 47), P(26, 44), P(8, 44)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillSmooth(ctx, [P(11, 44), P(23, 44), P(22, 26), P(12, 26)], UIColor(rgb: 0x6A6660))
            strokeSmooth(ctx, [P(11, 44), P(23, 44), P(22, 26), P(12, 26)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillSmooth(ctx, [P(11.5, 43), P(15, 43), P(15, 27), P(12, 27)], UIColor(rgb: 0x46433E))
            stroke(ctx, from: P(17, 27), to: P(17, 43), UIColor(rgb: 0x46433E), width: 0.8)
            fillSmooth(ctx, [P(9, 26), P(25, 26), P(24, 12), P(10, 12)], UIColor(rgb: 0x6A6660))
            strokeSmooth(ctx, [P(9, 26), P(25, 26), P(24, 12), P(10, 12)], UIColor(rgb: 0x0E0C08), width: 1)
            fillPolygon(ctx, [P(10, 12), P(24, 12), P(22, 9), P(12, 9)], UIColor(rgb: 0x8A8680))
            strokePolygon(ctx, [P(10, 12), P(24, 12), P(22, 9), P(12, 9)], UIColor(rgb: 0x0E0C08), width: 0.7)
            strokeCurve(ctx, [P(12, 18), P(17, 20), P(22, 18)], UIColor(rgb: 0x46433E), width: 1)
            fillPolygon(ctx, [P(14, 9), P(20, 9), P(19, 6), P(17, 8), P(15, 6)], UIColor(rgb: 0x8A8680))
            strokePolygon(ctx, [P(14, 9), P(20, 9), P(19, 6), P(17, 8), P(15, 6)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillPolygon(ctx, [P(15.5, 20), P(16.2, 42), P(17.8, 42), P(18.5, 20)], UIColor(rgb: 0x8A8680))
            strokePolygon(ctx, [P(15.5, 20), P(16.2, 42), P(17.8, 42), P(18.5, 20)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(10, 20), to: P(24, 20), UIColor(rgb: 0x8A8680), width: 1.6)
            fillPolygon(ctx, [P(2, 55), P(6, 51), P(9, 55)], UIColor(rgb: 0x6A6660))
            strokePolygon(ctx, [P(2, 55), P(6, 51), P(9, 55)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillPolygon(ctx, [P(27, 55), P(31, 52), P(33, 55)], UIColor(rgb: 0x6A6660))
            strokePolygon(ctx, [P(27, 55), P(31, 52), P(33, 55)], UIColor(rgb: 0x0E0C08), width: 0.6)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.03))
    }

    // MARK: - barricade

    /// Stakes and a cart's ribs, dragged across the street.
    static func barricade() -> Sprite {
        let image = render(CGSize(width: 44, height: 34)) { ctx in
            fillOval(ctx, CGRect(x: 4, y: 29, width: 36, height: 6), UIColor(rgb: 0x46433E))
            fillPolygon(ctx, [P(9.67, 31.31), P(10.19, 27.71), P(10.71, 24.27), P(11.22, 21.01), P(11.74, 17.91), P(12.26, 14.97), P(12.78, 12.19), P(11.22, 11.81), P(10.41, 14.53), P(9.59, 17.43), P(8.78, 20.49), P(7.96, 23.73), P(7.14, 27.13), P(6.33, 30.69)], UIColor(rgb: 0x4A3A28))
            strokePolygon(ctx, [P(9.67, 31.31), P(10.19, 27.71), P(10.71, 24.27), P(11.22, 21.01), P(11.74, 17.91), P(12.26, 14.97), P(12.78, 12.19), P(11.22, 11.81), P(10.41, 14.53), P(9.59, 17.43), P(8.78, 20.49), P(7.96, 23.73), P(7.14, 27.13), P(6.33, 30.69)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(10.4, 12), P(13.6, 13), P(12.4, 9)], UIColor(rgb: 0x6A5438))
            strokePolygon(ctx, [P(10.4, 12), P(13.6, 13), P(12.4, 9)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(17.69, 30.82), P(17.04, 26.08), P(16.39, 21.58), P(15.74, 17.3), P(15.09, 13.26), P(14.44, 9.46), P(13.79, 5.89), P(12.21, 6.11), P(12.56, 9.71), P(12.91, 13.54), P(13.26, 17.6), P(13.61, 21.89), P(13.96, 26.42), P(14.31, 31.18)], UIColor(rgb: 0x4A3A28))
            strokePolygon(ctx, [P(17.69, 30.82), P(17.04, 26.08), P(16.39, 21.58), P(15.74, 17.3), P(15.09, 13.26), P(14.44, 9.46), P(13.79, 5.89), P(12.21, 6.11), P(12.56, 9.71), P(12.91, 13.54), P(13.26, 17.6), P(13.61, 21.89), P(13.96, 26.42), P(14.31, 31.18)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(11.4, 6), P(14.6, 7), P(13.4, 3)], UIColor(rgb: 0x6A5438))
            strokePolygon(ctx, [P(11.4, 6), P(14.6, 7), P(13.4, 3)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(27.69, 31.2), P(28.04, 27.02), P(28.39, 23.05), P(28.74, 19.27), P(29.09, 15.69), P(29.44, 12.31), P(29.79, 9.12), P(28.21, 8.88), P(27.56, 12.02), P(26.91, 15.38), P(26.26, 18.93), P(25.61, 22.69), P(24.96, 26.64), P(24.31, 30.8)], UIColor(rgb: 0x4A3A28))
            strokePolygon(ctx, [P(27.69, 31.2), P(28.04, 27.02), P(28.39, 23.05), P(28.74, 19.27), P(29.09, 15.69), P(29.44, 12.31), P(29.79, 9.12), P(28.21, 8.88), P(27.56, 12.02), P(26.91, 15.38), P(26.26, 18.93), P(25.61, 22.69), P(24.96, 26.64), P(24.31, 30.8)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(27.4, 9), P(30.6, 10), P(29.4, 6)], UIColor(rgb: 0x6A5438))
            strokePolygon(ctx, [P(27.4, 9), P(30.6, 10), P(29.4, 6)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(36.66, 30.65), P(35.85, 27.48), P(35.03, 24.45), P(34.22, 21.56), P(33.4, 18.82), P(32.59, 16.23), P(31.77, 13.79), P(30.23, 14.21), P(30.75, 16.71), P(31.27, 19.35), P(31.78, 22.14), P(32.3, 25.06), P(32.82, 28.13), P(33.34, 31.35)], UIColor(rgb: 0x4A3A28))
            strokePolygon(ctx, [P(36.66, 30.65), P(35.85, 27.48), P(35.03, 24.45), P(34.22, 21.56), P(33.4, 18.82), P(32.59, 16.23), P(31.77, 13.79), P(30.23, 14.21), P(30.75, 16.71), P(31.27, 19.35), P(31.78, 22.14), P(32.3, 25.06), P(32.82, 28.13), P(33.34, 31.35)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(29.4, 14), P(32.6, 15), P(31.4, 11)], UIColor(rgb: 0x6A5438))
            strokePolygon(ctx, [P(29.4, 14), P(32.6, 15), P(31.4, 11)], UIColor(rgb: 0x0E0C08), width: 0.5)
            fillPolygon(ctx, [P(6.2, 23.99), P(11.54, 23.23), P(16.97, 22.73), P(22.52, 22.47), P(28.18, 22.47), P(33.97, 22.71), P(39.89, 23.2), P(40.11, 20.8), P(34.14, 20.21), P(28.26, 19.87), P(22.48, 19.78), P(16.81, 19.94), P(11.23, 20.35), P(5.8, 21.01)], UIColor(rgb: 0x6A5438))
            strokePolygon(ctx, [P(6.2, 23.99), P(11.54, 23.23), P(16.97, 22.73), P(22.52, 22.47), P(28.18, 22.47), P(33.97, 22.71), P(39.89, 23.2), P(40.11, 20.8), P(34.14, 20.21), P(28.26, 19.87), P(22.48, 19.78), P(16.81, 19.94), P(11.23, 20.35), P(5.8, 21.01)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 11.4, y: 20.2, width: 1.2, height: 1.2), UIColor(rgb: 0x8E8A80))
            fillOval(ctx, CGRect(x: 19.4, y: 20.2, width: 1.2, height: 1.2), UIColor(rgb: 0x8E8A80))
            fillOval(ctx, CGRect(x: 29.4, y: 20.2, width: 1.2, height: 1.2), UIColor(rgb: 0x8E8A80))
            fillPolygon(ctx, [P(9.24, 15.98), P(13.55, 15.23), P(17.88, 14.73), P(22.27, 14.47), P(26.73, 14.47), P(31.25, 14.7), P(35.86, 15.19), P(36.14, 12.81), P(31.47, 12.21), P(26.83, 11.87), P(22.23, 11.78), P(17.67, 11.94), P(13.17, 12.35), P(8.76, 13.02)], UIColor(rgb: 0x6A5438))
            strokePolygon(ctx, [P(9.24, 15.98), P(13.55, 15.23), P(17.88, 14.73), P(22.27, 14.47), P(26.73, 14.47), P(31.25, 14.7), P(35.86, 15.19), P(36.14, 12.81), P(31.47, 12.21), P(26.83, 11.87), P(22.23, 11.78), P(17.67, 11.94), P(13.17, 12.35), P(8.76, 13.02)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillOval(ctx, CGRect(x: 11.4, y: 12.2, width: 1.2, height: 1.2), UIColor(rgb: 0x8E8A80))
            fillOval(ctx, CGRect(x: 19.4, y: 12.2, width: 1.2, height: 1.2), UIColor(rgb: 0x8E8A80))
            fillOval(ctx, CGRect(x: 29.4, y: 12.2, width: 1.2, height: 1.2), UIColor(rgb: 0x8E8A80))
            fillPolygon(ctx, [P(30, 24), P(40, 20), P(41, 28), P(31, 31)], UIColor(rgb: 0x7A5A40))
            strokePolygon(ctx, [P(30, 24), P(40, 20), P(41, 28), P(31, 31)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 33, y: 23, width: 9, height: 9), UIColor(rgb: 0x3B2E20))
            strokeOval(ctx, CGRect(x: 33, y: 23, width: 9, height: 9), UIColor(rgb: 0x0E0C08), width: 0.8)
            stroke(ctx, from: P(33.5, 27.5), to: P(41.5, 27.5), UIColor(rgb: 0x2E2418), width: 0.7)
            stroke(ctx, from: P(37.5, 23.5), to: P(37.5, 31.5), UIColor(rgb: 0x2E2418), width: 0.7)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.06))
    }

    // MARK: - skullPile

    /// A heap of skulls, stacked on purpose.
    static func skullPile() -> Sprite {
        let image = render(CGSize(width: 40, height: 28)) { ctx in
            fillOval(ctx, CGRect(x: 3, y: 22, width: 34, height: 7), UIColor(rgb: 0x373228))
            fillSmooth(ctx, [P(3.5, 19.9), P(5.15, 15.5), P(9, 14.12), P(12.85, 15.5), P(14.5, 19.9), P(12.03, 23.75), P(5.97, 23.75)], UIColor(rgb: 0xD8CDB0))
            strokeSmooth(ctx, [P(3.5, 19.9), P(5.15, 15.5), P(9, 14.12), P(12.85, 15.5), P(14.5, 19.9), P(12.03, 23.75), P(5.97, 23.75)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 3.88, y: 17.98, width: 3.03, height: 2.75), UIColor(rgb: 0x16110E))
            fillOval(ctx, CGRect(x: 9.1, y: 17.98, width: 3.03, height: 2.75), UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(8, 20.73), P(9.54, 22.38), P(6.9, 22.38)], UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(5.97, 23.2), P(12.03, 23.2), P(11.2, 25.68), P(6.8, 25.68)], UIColor(rgb: 0xA89C80))
            strokePolygon(ctx, [P(5.97, 23.2), P(12.03, 23.2), P(11.2, 25.68), P(6.8, 25.68)], UIColor(rgb: 0x0E0C08), width: 0.5)
            stroke(ctx, from: P(7.35, 23.48), to: P(7.35, 25.29), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(9.28, 23.48), to: P(9.28, 25.29), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(11.2, 23.48), to: P(11.2, 25.29), UIColor(rgb: 0x16110E), width: 0.35)
            fillSmooth(ctx, [P(13, 20.8), P(14.8, 16), P(19, 14.5), P(23.2, 16), P(25, 20.8), P(22.3, 25), P(15.7, 25)], UIColor(rgb: 0xD8CDB0))
            strokeSmooth(ctx, [P(13, 20.8), P(14.8, 16), P(19, 14.5), P(23.2, 16), P(25, 20.8), P(22.3, 25), P(15.7, 25)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 14.9, y: 18.7, width: 3.3, height: 3), UIColor(rgb: 0x16110E))
            fillOval(ctx, CGRect(x: 20.6, y: 18.7, width: 3.3, height: 3), UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(19.4, 21.7), P(21.08, 23.5), P(18.2, 23.5)], UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(15.7, 24.4), P(22.3, 24.4), P(21.4, 27.1), P(16.6, 27.1)], UIColor(rgb: 0xA89C80))
            strokePolygon(ctx, [P(15.7, 24.4), P(22.3, 24.4), P(21.4, 27.1), P(16.6, 27.1)], UIColor(rgb: 0x0E0C08), width: 0.5)
            stroke(ctx, from: P(17.2, 24.7), to: P(17.2, 26.68), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(19.3, 24.7), to: P(19.3, 26.68), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(21.4, 24.7), to: P(21.4, 26.68), UIColor(rgb: 0x16110E), width: 0.35)
            fillSmooth(ctx, [P(24, 20), P(25.5, 16), P(29, 14.75), P(32.5, 16), P(34, 20), P(31.75, 23.5), P(26.25, 23.5)], UIColor(rgb: 0xA89C80))
            strokeSmooth(ctx, [P(24, 20), P(25.5, 16), P(29, 14.75), P(32.5, 16), P(34, 20), P(31.75, 23.5), P(26.25, 23.5)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 26.25, y: 18.25, width: 2.75, height: 2.5), UIColor(rgb: 0x16110E))
            fillOval(ctx, CGRect(x: 31, y: 18.25, width: 2.75, height: 2.5), UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(30, 20.75), P(31.4, 22.25), P(29, 22.25)], UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(26.25, 23), P(31.75, 23), P(31, 25.25), P(27, 25.25)], UIColor(rgb: 0xA89C80))
            strokePolygon(ctx, [P(26.25, 23), P(31.75, 23), P(31, 25.25), P(27, 25.25)], UIColor(rgb: 0x0E0C08), width: 0.5)
            stroke(ctx, from: P(27.5, 23.25), to: P(27.5, 24.9), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(29.25, 23.25), to: P(29.25, 24.9), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(31, 23.25), to: P(31, 24.9), UIColor(rgb: 0x16110E), width: 0.35)
            fillSmooth(ctx, [P(8.8, 12.96), P(10.36, 8.8), P(14, 7.5), P(17.64, 8.8), P(19.2, 12.96), P(16.86, 16.6), P(11.14, 16.6)], UIColor(rgb: 0xD8CDB0))
            strokeSmooth(ctx, [P(8.8, 12.96), P(10.36, 8.8), P(14, 7.5), P(17.64, 8.8), P(19.2, 12.96), P(16.86, 16.6), P(11.14, 16.6)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 10.7, y: 11.14, width: 2.86, height: 2.6), UIColor(rgb: 0x16110E))
            fillOval(ctx, CGRect(x: 15.64, y: 11.14, width: 2.86, height: 2.6), UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(14.6, 13.74), P(16.06, 15.3), P(13.56, 15.3)], UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(11.14, 16.08), P(16.86, 16.08), P(16.08, 18.42), P(11.92, 18.42)], UIColor(rgb: 0xA89C80))
            strokePolygon(ctx, [P(11.14, 16.08), P(16.86, 16.08), P(16.08, 18.42), P(11.92, 18.42)], UIColor(rgb: 0x0E0C08), width: 0.5)
            stroke(ctx, from: P(12.44, 16.34), to: P(12.44, 18.06), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(14.26, 16.34), to: P(14.26, 18.06), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(16.08, 16.34), to: P(16.08, 18.06), UIColor(rgb: 0x16110E), width: 0.35)
            fillSmooth(ctx, [P(19.2, 13.04), P(20.64, 9.2), P(24, 8), P(27.36, 9.2), P(28.8, 13.04), P(26.64, 16.4), P(21.36, 16.4)], UIColor(rgb: 0xA89C80))
            strokeSmooth(ctx, [P(19.2, 13.04), P(20.64, 9.2), P(24, 8), P(27.36, 9.2), P(28.8, 13.04), P(26.64, 16.4), P(21.36, 16.4)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 19.9, y: 11.36, width: 2.64, height: 2.4), UIColor(rgb: 0x16110E))
            fillOval(ctx, CGRect(x: 24.46, y: 11.36, width: 2.64, height: 2.4), UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(23.5, 13.76), P(24.84, 15.2), P(22.54, 15.2)], UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(21.36, 15.92), P(26.64, 15.92), P(25.92, 18.08), P(22.08, 18.08)], UIColor(rgb: 0xA89C80))
            strokePolygon(ctx, [P(21.36, 15.92), P(26.64, 15.92), P(25.92, 18.08), P(22.08, 18.08)], UIColor(rgb: 0x0E0C08), width: 0.5)
            stroke(ctx, from: P(22.56, 16.16), to: P(22.56, 17.74), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(24.24, 16.16), to: P(24.24, 17.74), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(25.92, 16.16), to: P(25.92, 17.74), UIColor(rgb: 0x16110E), width: 0.35)
            fillSmooth(ctx, [P(14, 6), P(15.5, 2), P(19, 0.75), P(22.5, 2), P(24, 6), P(21.75, 9.5), P(16.25, 9.5)], UIColor(rgb: 0xA89C80))
            strokeSmooth(ctx, [P(14, 6), P(15.5, 2), P(19, 0.75), P(22.5, 2), P(24, 6), P(21.75, 9.5), P(16.25, 9.5)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 15.45, y: 4.25, width: 2.75, height: 2.5), UIColor(rgb: 0x16110E))
            fillOval(ctx, CGRect(x: 20.2, y: 4.25, width: 2.75, height: 2.5), UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(19.2, 6.75), P(20.6, 8.25), P(18.2, 8.25)], UIColor(rgb: 0x16110E))
            fillPolygon(ctx, [P(16.25, 9), P(21.75, 9), P(21, 11.25), P(17, 11.25)], UIColor(rgb: 0xA89C80))
            strokePolygon(ctx, [P(16.25, 9), P(21.75, 9), P(21, 11.25), P(17, 11.25)], UIColor(rgb: 0x0E0C08), width: 0.5)
            stroke(ctx, from: P(17.5, 9.25), to: P(17.5, 10.9), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(19.25, 9.25), to: P(19.25, 10.9), UIColor(rgb: 0x16110E), width: 0.35)
            stroke(ctx, from: P(21, 9.25), to: P(21, 10.9), UIColor(rgb: 0x16110E), width: 0.35)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.07))
    }

    // MARK: - blackObelisk

    /// A stone with writing on it that will not stay still.
    static func blackObelisk() -> Sprite {
        let image = render(CGSize(width: 32, height: 66)) { ctx in
            fillOval(ctx, CGRect(x: 5, y: 59, width: 22, height: 8), UIColor(rgb: 0x18141C))
            radialGradient(ctx, center: P(16, 34), radius: 20, inner: UIColor(rgb: 0x5A3F8C, alpha: 0.3), outer: UIColor(rgb: 0x5A3F8C, alpha: 0))
            fillPolygon(ctx, [P(10, 63), P(12, 12), P(16, 4), P(20, 12), P(22, 63)], UIColor(rgb: 0x1E1A24))
            strokePolygon(ctx, [P(10, 63), P(12, 12), P(16, 4), P(20, 12), P(22, 63)], UIColor(rgb: 0x0E0C08), width: 1)
            fillPolygon(ctx, [P(16, 4), P(20, 12), P(22, 63), P(16.5, 63)], UIColor(rgb: 0x46434B))
            fillPolygon(ctx, [P(10, 63), P(12, 12), P(16, 4), P(15.5, 63)], UIColor(rgb: 0x100E13))
            stroke(ctx, from: P(14.25, 16), to: P(17.75, 16), UIColor(rgb: 0xC79BFF), width: 0.9)
            stroke(ctx, from: P(16, 14), to: P(16, 18), UIColor(rgb: 0xC79BFF), width: 0.7)
            stroke(ctx, from: P(14.65, 23), to: P(17.35, 23), UIColor(rgb: 0xC79BFF), width: 0.9)
            fillOval(ctx, CGRect(x: 17.85, y: 22.5, width: 1, height: 1), UIColor(rgb: 0xC79BFF))
            stroke(ctx, from: P(15.05, 30), to: P(16.95, 30), UIColor(rgb: 0xC79BFF), width: 0.9)
            stroke(ctx, from: P(16, 28), to: P(16, 32), UIColor(rgb: 0xC79BFF), width: 0.7)
            stroke(ctx, from: P(14.25, 37), to: P(17.75, 37), UIColor(rgb: 0xC79BFF), width: 0.9)
            fillOval(ctx, CGRect(x: 18.25, y: 36.5, width: 1, height: 1), UIColor(rgb: 0xC79BFF))
            stroke(ctx, from: P(14.65, 44), to: P(17.35, 44), UIColor(rgb: 0xC79BFF), width: 0.9)
            stroke(ctx, from: P(16, 42), to: P(16, 46), UIColor(rgb: 0xC79BFF), width: 0.7)
            stroke(ctx, from: P(15.05, 51), to: P(16.95, 51), UIColor(rgb: 0xC79BFF), width: 0.9)
            fillOval(ctx, CGRect(x: 17.45, y: 50.5, width: 1, height: 1), UIColor(rgb: 0xC79BFF))
            fillPolygon(ctx, [P(4, 63), P(7, 55), P(10, 63)], UIColor(rgb: 0x1E1A24))
            strokePolygon(ctx, [P(4, 63), P(7, 55), P(10, 63)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillPolygon(ctx, [P(22, 63), P(25, 57), P(27, 63)], UIColor(rgb: 0x1E1A24))
            strokePolygon(ctx, [P(22, 63), P(25, 57), P(27, 63)], UIColor(rgb: 0x0E0C08), width: 0.6)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.03))
    }
}
