import UIKit

// Generated by tools/art/loot.py. Edit the Python and rerun it; do not edit
// this file by hand.

/// What the horde leaves behind: draughts, a lodestone, and three grades of
/// chest. They stand on the ground and are anchored at their base. The
/// drawing primitives these call live in PlaceholderArt+Drawing.swift.
extension PlaceholderArt {

    // MARK: - dropVial

    /// A red draught in a stoppered flask. It is what it looks like.
    static func dropVial() -> Sprite {
        let image = render(CGSize(width: 18, height: 24)) { ctx in
            fillOval(ctx, CGRect(x: 3, y: 19, width: 12, height: 4.5), UIColor(rgb: 0x23170A))
            radialGradient(ctx, center: P(9, 13), radius: 9, inner: UIColor(rgb: 0xB8323A, alpha: 0.35), outer: UIColor(rgb: 0xB8323A, alpha: 0))
            fillPolygon(ctx, [P(7, 5), P(11, 5), P(11, 10), P(7, 10)], UIColor(rgb: 0xD8E8F0))
            strokePolygon(ctx, [P(7, 5), P(11, 5), P(11, 10), P(7, 10)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(6.4, 1.6), P(11.6, 1.6), P(11.2, 5), P(6.8, 5)], UIColor(rgb: 0x7E5C36))
            strokePolygon(ctx, [P(6.4, 1.6), P(11.6, 1.6), P(11.2, 5), P(6.8, 5)], UIColor(rgb: 0x0E0C08), width: 0.7)
            stroke(ctx, from: P(7.6, 2.8), to: P(10.4, 2.8), UIColor(rgb: 0x33220F), width: 0.5)
            fillSmooth(ctx, [P(9, 9), P(14, 13), P(15, 16.5), P(12.6, 20), P(5.4, 20), P(3, 16.5), P(4, 13)], UIColor(rgb: 0xD8E8F0))
            strokeSmooth(ctx, [P(9, 9), P(14, 13), P(15, 16.5), P(12.6, 20), P(5.4, 20), P(3, 16.5), P(4, 13)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillSmooth(ctx, [P(9, 11.6), P(13.2, 14), P(14, 16.6), P(12, 19.4), P(6, 19.4), P(4.2, 16.6), P(4.8, 14)], UIColor(rgb: 0xB8323A))
            fillSmooth(ctx, [P(5, 16.6), P(13, 16.6), P(12, 19.2), P(6, 19.2)], UIColor(rgb: 0x6E1E24))
            fillOval(ctx, CGRect(x: 5.6, y: 13, width: 2.6, height: 3.4), UIColor(rgb: 0xEFF5F9))
            fillOval(ctx, CGRect(x: 10.9, y: 14.3, width: 1.4, height: 1.4), UIColor(rgb: 0xE2ADB0))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.08))
    }

    // MARK: - dropMagnet

    /// A horseshoe of lodestone. Everything loose wants to be near it.
    static func dropMagnet() -> Sprite {
        let image = render(CGSize(width: 22, height: 22)) { ctx in
            fillOval(ctx, CGRect(x: 3, y: 16.6, width: 16, height: 5), UIColor(rgb: 0x23170A))
            radialGradient(ctx, center: P(11, 11), radius: 11, inner: UIColor(rgb: 0xC9A24A, alpha: 0.3), outer: UIColor(rgb: 0xC9A24A, alpha: 0))
            fillPolygon(ctx, [P(3, 19), P(8, 19), P(8.4, 11), P(10, 7.6), P(12, 7.6), P(13.6, 11), P(14, 19), P(19, 19), P(19, 10), P(15.4, 3.4), P(11, 1.6), P(6.6, 3.4), P(3, 10)], UIColor(rgb: 0xC4CAD2))
            strokePolygon(ctx, [P(3, 19), P(8, 19), P(8.4, 11), P(10, 7.6), P(12, 7.6), P(13.6, 11), P(14, 19), P(19, 19), P(19, 10), P(15.4, 3.4), P(11, 1.6), P(6.6, 3.4), P(3, 10)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillPolygon(ctx, [P(11, 1.6), P(15.4, 3.4), P(19, 10), P(19, 19), P(14, 19), P(13.6, 11), P(12, 7.6), P(11, 7.6)], UIColor(rgb: 0x93979D))
            fillPolygon(ctx, [P(3, 19), P(8, 19), P(8.1, 14.4), P(3, 14.4)], UIColor(rgb: 0xC23A34))
            strokePolygon(ctx, [P(3, 19), P(8, 19), P(8.1, 14.4), P(3, 14.4)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(14, 19), P(19, 19), P(19, 14.4), P(13.9, 14.4)], UIColor(rgb: 0x3A5AC2))
            strokePolygon(ctx, [P(14, 19), P(19, 19), P(19, 14.4), P(13.9, 14.4)], UIColor(rgb: 0x0E0C08), width: 0.7)
            strokeCurve(ctx, [P(5, 10), P(7.6, 4.6), P(11, 3)], UIColor(rgb: 0xE1E4E8), width: 0.8)
            fillOval(ctx, CGRect(x: 10.3, y: 0.3, width: 1.4, height: 1.4), UIColor(rgb: 0xF0D58A))
            fillOval(ctx, CGRect(x: 5.3, y: 0.3, width: 1.4, height: 1.4), UIColor(rgb: 0xF0D58A))
            fillOval(ctx, CGRect(x: 15.3, y: 0.3, width: 1.4, height: 1.4), UIColor(rgb: 0xF0D58A))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.09))
    }

    // MARK: - dropChestCache

    /// A strongbox with a hasp. Somebody meant to come back for it.
    static func dropChestCache() -> Sprite {
        let image = render(CGSize(width: 30, height: 24)) { ctx in
            fillOval(ctx, CGRect(x: 2, y: 18, width: 26, height: 6), UIColor(rgb: 0x23170A))
            fillPolygon(ctx, [P(4, 21), P(26, 21), P(26, 11), P(4, 11)], UIColor(rgb: 0x5A3E26))
            strokePolygon(ctx, [P(4, 21), P(26, 21), P(26, 11), P(4, 11)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillPolygon(ctx, [P(4, 11), P(26, 11), P(24.5, 4.5), P(5.5, 4.5)], UIColor(rgb: 0x7E5C36))
            strokePolygon(ctx, [P(4, 11), P(26, 11), P(24.5, 4.5), P(5.5, 4.5)], UIColor(rgb: 0x0E0C08), width: 0.9)
            stroke(ctx, from: P(4.6, 17.5), to: P(25.4, 17.5), UIColor(rgb: 0x33220F), width: 0.5)
            stroke(ctx, from: P(4.6, 14), to: P(25.4, 14), UIColor(rgb: 0x33220F), width: 0.5)
            stroke(ctx, from: P(6.6, 7), to: P(23.4, 7), UIColor(rgb: 0x33220F), width: 0.5)
            fillPolygon(ctx, [P(7, 4.6), P(9.4, 4.6), P(9.4, 20.6), P(7, 20.6)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(7, 4.6), P(9.4, 4.6), P(9.4, 20.6), P(7, 20.6)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillPolygon(ctx, [P(20.6, 4.6), P(23, 4.6), P(23, 20.6), P(20.6, 20.6)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(20.6, 4.6), P(23, 4.6), P(23, 20.6), P(20.6, 20.6)], UIColor(rgb: 0x0E0C08), width: 0.6)
            fillPolygon(ctx, [P(13, 9), P(17, 9), P(17, 14), P(13, 14)], UIColor(rgb: 0x9A968C))
            strokePolygon(ctx, [P(13, 9), P(17, 9), P(17, 14), P(13, 14)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillOval(ctx, CGRect(x: 14.1, y: 10.7, width: 1.8, height: 1.8), UIColor(rgb: 0x0E0C08))
            fillPolygon(ctx, [P(4, 21), P(9, 21), P(4, 17)], UIColor(rgb: 0x7A5A40))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.08))
    }

    // MARK: - dropChestChest

    /// A banded iron chest. It was locked, and then someone made an argument.
    static func dropChestChest() -> Sprite {
        let image = render(CGSize(width: 34, height: 28)) { ctx in
            fillOval(ctx, CGRect(x: 2, y: 21.6, width: 30, height: 6.4), UIColor(rgb: 0x23170A))
            radialGradient(ctx, center: P(17, 14), radius: 16, inner: UIColor(rgb: 0x6AD0F0, alpha: 0.18), outer: UIColor(rgb: 0x6AD0F0, alpha: 0))
            fillPolygon(ctx, [P(4, 25), P(30, 25), P(30, 14), P(4, 14)], UIColor(rgb: 0x513722))
            strokePolygon(ctx, [P(4, 25), P(30, 25), P(30, 14), P(4, 14)], UIColor(rgb: 0x0E0C08), width: 1)
            fillSmooth(ctx, [P(4, 14), P(5.4, 7.4), P(11, 3.4), P(17, 2.4), P(23, 3.4), P(28.6, 7.4), P(30, 14)], UIColor(rgb: 0x7E5C36))
            strokeSmooth(ctx, [P(4, 14), P(5.4, 7.4), P(11, 3.4), P(17, 2.4), P(23, 3.4), P(28.6, 7.4), P(30, 14)], UIColor(rgb: 0x0E0C08), width: 1)
            strokeCurve(ctx, [P(7, 7), P(17, 4), P(27, 7)], UIColor(rgb: 0xA48C72), width: 0.7)
            fillPolygon(ctx, [P(5.6, 5), P(9, 5), P(9, 24.6), P(5.6, 24.6)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(5.6, 5), P(9, 5), P(9, 24.6), P(5.6, 24.6)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(6.2, 6), to: P(6.2, 24), UIColor(rgb: 0x9A968C), width: 0.5)
            fillOval(ctx, CGRect(x: 6.7, y: 8.4, width: 1.2, height: 1.2), UIColor(rgb: 0x9A968C))
            fillOval(ctx, CGRect(x: 6.7, y: 16.4, width: 1.2, height: 1.2), UIColor(rgb: 0x9A968C))
            fillOval(ctx, CGRect(x: 6.7, y: 21.4, width: 1.2, height: 1.2), UIColor(rgb: 0x9A968C))
            fillPolygon(ctx, [P(15.2, 5), P(18.6, 5), P(18.6, 24.6), P(15.2, 24.6)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(15.2, 5), P(18.6, 5), P(18.6, 24.6), P(15.2, 24.6)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(15.8, 6), to: P(15.8, 24), UIColor(rgb: 0x9A968C), width: 0.5)
            fillOval(ctx, CGRect(x: 16.3, y: 8.4, width: 1.2, height: 1.2), UIColor(rgb: 0x9A968C))
            fillOval(ctx, CGRect(x: 16.3, y: 16.4, width: 1.2, height: 1.2), UIColor(rgb: 0x9A968C))
            fillOval(ctx, CGRect(x: 16.3, y: 21.4, width: 1.2, height: 1.2), UIColor(rgb: 0x9A968C))
            fillPolygon(ctx, [P(25.2, 5), P(28.6, 5), P(28.6, 24.6), P(25.2, 24.6)], UIColor(rgb: 0x5E5A54))
            strokePolygon(ctx, [P(25.2, 5), P(28.6, 5), P(28.6, 24.6), P(25.2, 24.6)], UIColor(rgb: 0x0E0C08), width: 0.6)
            stroke(ctx, from: P(25.8, 6), to: P(25.8, 24), UIColor(rgb: 0x9A968C), width: 0.5)
            fillOval(ctx, CGRect(x: 26.3, y: 8.4, width: 1.2, height: 1.2), UIColor(rgb: 0x9A968C))
            fillOval(ctx, CGRect(x: 26.3, y: 16.4, width: 1.2, height: 1.2), UIColor(rgb: 0x9A968C))
            fillOval(ctx, CGRect(x: 26.3, y: 21.4, width: 1.2, height: 1.2), UIColor(rgb: 0x9A968C))
            fillPolygon(ctx, [P(14.4, 11), P(19.6, 11), P(19.6, 18), P(14.4, 18)], UIColor(rgb: 0xC9A24A))
            strokePolygon(ctx, [P(14.4, 11), P(19.6, 11), P(19.6, 18), P(14.4, 18)], UIColor(rgb: 0x0E0C08), width: 0.8)
            fillOval(ctx, CGRect(x: 16, y: 13.4, width: 2, height: 2), UIColor(rgb: 0x0E0C08))
            fillPolygon(ctx, [P(16.4, 14.8), P(17.6, 14.8), P(17.8, 17), P(16.2, 17)], UIColor(rgb: 0x0E0C08))
            strokeCurve(ctx, [P(14.8, 11), P(14.8, 8.4), P(19.2, 8.4), P(19.2, 11)], UIColor(rgb: 0x9A968C), width: 0.9)
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.07))
    }

    // MARK: - dropChestHoard

    /// Gold heaped past the lid. It gives off a light of its own.
    static func dropChestHoard() -> Sprite {
        let image = render(CGSize(width: 38, height: 40)) { ctx in
            fillOval(ctx, CGRect(x: 1, y: 33.4, width: 36, height: 7), UIColor(rgb: 0x23170A))
            radialGradient(ctx, center: P(19, 21), radius: 18, inner: UIColor(rgb: 0xC9A24A, alpha: 0.5), outer: UIColor(rgb: 0xC9A24A, alpha: 0))
            radialGradient(ctx, center: P(19, 18), radius: 11, inner: UIColor(rgb: 0xF0D58A, alpha: 0.35), outer: UIColor(rgb: 0xF0D58A, alpha: 0))
            fillPolygon(ctx, [P(4, 37), P(34, 37), P(34, 25), P(4, 25)], UIColor(rgb: 0x553A24))
            strokePolygon(ctx, [P(4, 37), P(34, 37), P(34, 25), P(4, 25)], UIColor(rgb: 0x0E0C08), width: 1)
            fillPolygon(ctx, [P(5, 25), P(8.4, 25), P(8.4, 36.6), P(5, 36.6)], UIColor(rgb: 0xC9A24A))
            strokePolygon(ctx, [P(5, 25), P(8.4, 25), P(8.4, 36.6), P(5, 36.6)], UIColor(rgb: 0x0E0C08), width: 0.7)
            stroke(ctx, from: P(5.8, 25.6), to: P(5.8, 36), UIColor(rgb: 0xF0D58A), width: 0.5)
            fillPolygon(ctx, [P(16.4, 25), P(19.8, 25), P(19.8, 36.6), P(16.4, 36.6)], UIColor(rgb: 0xC9A24A))
            strokePolygon(ctx, [P(16.4, 25), P(19.8, 25), P(19.8, 36.6), P(16.4, 36.6)], UIColor(rgb: 0x0E0C08), width: 0.7)
            stroke(ctx, from: P(17.2, 25.6), to: P(17.2, 36), UIColor(rgb: 0xF0D58A), width: 0.5)
            fillPolygon(ctx, [P(28.6, 25), P(32, 25), P(32, 36.6), P(28.6, 36.6)], UIColor(rgb: 0xC9A24A))
            strokePolygon(ctx, [P(28.6, 25), P(32, 25), P(32, 36.6), P(28.6, 36.6)], UIColor(rgb: 0x0E0C08), width: 0.7)
            stroke(ctx, from: P(29.4, 25.6), to: P(29.4, 36), UIColor(rgb: 0xF0D58A), width: 0.5)
            stroke(ctx, from: P(4.6, 25), to: P(33.4, 25), UIColor(rgb: 0x8A6A26), width: 1)
            fillPolygon(ctx, [P(3.4, 25), P(34.6, 25), P(32, 19), P(6, 19)], UIColor(rgb: 0x48311E))
            strokePolygon(ctx, [P(3.4, 25), P(34.6, 25), P(32, 19), P(6, 19)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillSmooth(ctx, [P(6, 19.4), P(11, 14), P(19, 11), P(27, 14), P(32, 19.4)], UIColor(rgb: 0xC9A24A))
            strokeSmooth(ctx, [P(6, 19.4), P(11, 14), P(19, 11), P(27, 14), P(32, 19.4)], UIColor(rgb: 0x0E0C08), width: 0.9)
            fillSmooth(ctx, [P(10, 19), P(14, 15), P(19, 13), P(24, 15), P(28, 19)], UIColor(rgb: 0xF0D58A))
            fillOval(ctx, CGRect(x: 11.2, y: 16.2, width: 1.6, height: 1.6), UIColor(rgb: 0x8A6A26))
            fillOval(ctx, CGRect(x: 16.2, y: 13.8, width: 1.6, height: 1.6), UIColor(rgb: 0x8A6A26))
            fillOval(ctx, CGRect(x: 22.2, y: 14.8, width: 1.6, height: 1.6), UIColor(rgb: 0x8A6A26))
            fillOval(ctx, CGRect(x: 26.2, y: 16.8, width: 1.6, height: 1.6), UIColor(rgb: 0x8A6A26))
            fillOval(ctx, CGRect(x: 6.4, y: 33.84, width: 5.2, height: 3.38), UIColor(rgb: 0xC9A24A))
            strokeOval(ctx, CGRect(x: 6.4, y: 33.84, width: 5.2, height: 3.38), UIColor(rgb: 0x0E0C08), width: 0.5)
            stroke(ctx, from: P(7.7, 35.01), to: P(10.04, 35.01), UIColor(rgb: 0xF0D58A), width: 0.5)
            fillOval(ctx, CGRect(x: 27.2, y: 34.12, width: 5.6, height: 3.64), UIColor(rgb: 0xC9A24A))
            strokeOval(ctx, CGRect(x: 27.2, y: 34.12, width: 5.6, height: 3.64), UIColor(rgb: 0x0E0C08), width: 0.5)
            stroke(ctx, from: P(28.6, 35.38), to: P(31.12, 35.38), UIColor(rgb: 0xF0D58A), width: 0.5)
            fillOval(ctx, CGRect(x: 0.4, y: 35.08, width: 4.4, height: 2.86), UIColor(rgb: 0xC9A24A))
            strokeOval(ctx, CGRect(x: 0.4, y: 35.08, width: 4.4, height: 2.86), UIColor(rgb: 0x0E0C08), width: 0.5)
            stroke(ctx, from: P(1.5, 36.07), to: P(3.48, 36.07), UIColor(rgb: 0xF0D58A), width: 0.5)
            fillPolygon(ctx, [P(19, 4), P(22.6, 8.6), P(19, 12.6), P(15.4, 8.6)], UIColor(rgb: 0x6AD0F0))
            strokePolygon(ctx, [P(19, 4), P(22.6, 8.6), P(19, 12.6), P(15.4, 8.6)], UIColor(rgb: 0x0E0C08), width: 0.7)
            fillPolygon(ctx, [P(19, 4), P(22.6, 8.6), P(19, 8.6)], UIColor(rgb: 0xADE5F6))
            fillOval(ctx, CGRect(x: 16.7, y: 6.7, width: 1.8, height: 1.8), UIColor(rgb: 0xE4FAFF))
        }
        return Sprite(image: image, anchor: CGPoint(x: 0.5, y: 0.05))
    }
}
