import Foundation

// Generated by tools/art/legacy_icons.py. Edit the Python and rerun it; do not
// edit this file by hand.

/// The Legacy board's icons as path strings on a 24 x 24 grid. See
/// `LegacyGlyph` for how they are read and drawn.
enum LegacyGlyphData {
    /// (style, path) pairs, drawn in order.
    static let shapes: [String: [(style: String, path: String)]] = [
        "blade": [
            ("fill", "M12 0.8 L15.2 4.2 L15.2 15.2 L8.8 15.2 L8.8 4.2 Z"),
            ("fill", "M3.6 14.8 Q12 12.8 20.4 14.8 L20.4 17.6 Q12 15.8 3.6 17.6 Z"),
            ("fill", "M10.6 17 L13.4 17 L13.4 21 L10.6 21 Z"),
            ("fill", "E 12 22.1 1.6 1.6"),
            ("stroke:1:0.4", "M12 3.6 L12 14"),
        ],
        "focus": [
            ("fill", "M1 12 Q12 1.6 23 12 Q12 22.4 1 12 Z"),
            ("shade", "E 12 12 5 5"),
            ("fill", "E 12 12 2.2 2.2"),
            ("fill", "E 10.6 10.6 1 1"),
        ],
        "fortune": [
            ("fill", "E 8.1 8.1 4.6 4.6"),
            ("fill", "E 15.9 8.1 4.6 4.6"),
            ("fill", "E 8.1 15.9 4.6 4.6"),
            ("fill", "E 15.9 15.9 4.6 4.6"),
            ("stroke:1.7", "M12 12 Q13.4 18.5 9.4 23"),
            ("stroke:0.8:0.3", "M12 12 L6.6 6.6 M12 12 L17.4 6.6 M12 12 L6.6 17.4 M12 12 L17.4 17.4"),
        ],
        "shadow": [
            ("fill", "M12 1.2 C6.4 1.6 3.4 6.6 4.4 12.6 L2.4 22.8 L21.6 22.8 L19.6 12.6 C20.6 6.6 17.6 1.6 12 1.2 Z"),
            ("shade", "M12 6.4 C8.8 6.4 7.2 9.6 7.7 13 C8.1 15.8 9.8 17 12 17 C14.2 17 15.9 15.8 16.3 13 C16.8 9.6 15.2 6.4 12 6.4 Z"),
            ("fill", "E 10.1 12 1 1.3"),
            ("fill", "E 13.9 12 1 1.3"),
        ],
        "bond": [
            ("fill", "M12 12 C8.4 12 5.6 15.2 5.6 18.2 C5.6 20.8 8 21.6 10.2 21.1 C11.2 20.9 11.6 20.6 12 20.6 C12.4 20.6 12.8 20.9 13.8 21.1 C16 21.6 18.4 20.8 18.4 18.2 C18.4 15.2 15.6 12 12 12 Z"),
            ("fill", "E 4.6 10.4 2.1 2.9"),
            ("fill", "E 9.2 5.8 2.2 3.1"),
            ("fill", "E 14.8 5.8 2.2 3.1"),
            ("fill", "E 19.4 10.4 2.1 2.9"),
        ],
        "fate": [
            ("fill", "M5.2 1.6 L18.8 1.6 L18.8 3.8 Q18.8 8.6 13.6 12 Q18.8 15.4 18.8 20.2 L18.8 22.4 L5.2 22.4 L5.2 20.2 Q5.2 15.4 10.4 12 Q5.2 8.6 5.2 3.8 Z"),
            ("shade", "M8.6 19.6 Q12 15.4 15.4 19.6 Z"),
            ("shade", "M9 4.4 L15 4.4 Q14.4 6.6 12 8.4 Q9.6 6.6 9 4.4 Z"),
            ("stroke:0.8:0.5", "M12 9.4 L12 15"),
        ],
        "echo": [
            ("fill", "E 12 12 2.8 2.8"),
            ("stroke:1.7", "E 12 12 6.2 6.2"),
            ("stroke:1.7:0.65", "E 12 12 10.2 10.2"),
        ],
    ]
}
